### ISSUE TITLE
Import dates option in Tempest?

### ISSUE THREAD

**Issue by amilesj** [beast-dev/beast-mcmc#1001]
The Tempest paper states that you can load dates from a tab-delimited table, but I am not seeing and import dates option. I just downloaded v1.5.1 and tried the java executable version on a Linux machine and OS X version on a Mac. Am I missing something, or has this not been incorporated yet? Thanks!

**Comment by rambaut** [comment]
There should be an 'Import Dates' option in the File menu:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/686405/41932839-1153a93c-797a-11e8-8e83-90afd32ada3d.png">

**Comment by amilesj** [comment]
Hm weird...mine doesn't have that.  I just downloaded from: http://tree.bio.ed.ac.uk/software/tempest/

![screen shot 2018-06-26 at 11 54 14 am](https://user-images.githubusercontent.com/20647069/41933088-b9638798-7937-11e8-8930-9bf38a0b6f81.png)
![screen shot 2018-06-26 at 11 54 00 am](https://user-images.githubusercontent.com/20647069/41933089-b9786f0a-7937-11e8-9a55-56f14c9e4385.png)

**Comment by rambaut** [comment]
I agree. Yours doesn't have that option. I will investigate.

**Comment by arturotorreso** [comment]
Any follow up in this issue? I have the same problem with the v1.5.1 in a OS X version on a Mac. So far I bypassed it by putting the dates on the sample name, but it would be great if a table could be imported. 

Thanks for your support!

**Comment by andrew-rothstein** [comment]
Would appreciate an update for this too! I have Tempest v. 1.5.1 and I have no import dates option. Thank you!

**Comment by chidwi** [comment]
following!

**Comment by rambaut** [comment]
TEMPEST v1.5.3 was released
