### ISSUE TITLE
bug beauti 1.10.0 setting GTR model

### ISSUE THREAD

**Issue by dbajpp0** [beast-dev/beast-mcmc#1002]
If I select the GTR model in beauti 1.10.0 I got this error in a pop-up:
"Illegal argument Exception"
"Parameter with name, gtr, is unknown"
Afterwards, every time that I click a tab the pop-up appears again. The pop-up also appears when I am trying to generate the xml file. The error does not occur if I select other models such as JC, TRN, HKY.
Thanks for this great software.
Best,
Joan

**Comment by rambaut** [comment]
Assume fixed at some point. Closing.
