### ISSUE TITLE
Synchronize BEAST downloads for v1.10.1

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#1003]
After we have fixed some more issues, we should make sure that our downloads for the different platforms contain the same fixes. For example, currently the Mac binaries no longer generate a BEAUti error message for the GTR model, but the Linux tar.gz does:
https://groups.google.com/forum/#!topic/beast-users/D8u2KRN2JLQ%5B1-25%5D

**Comment by rambaut** [comment]
This will be done for the v1.10.1 release
