### ISSUE TITLE
Issue with BEAUti GUI

### ISSUE THREAD

**Issue by samsledje** [beast-dev/beast-mcmc#1008]
I have version 1.10 of BEAST for Linux, and the BEAUti GUI will not let me select gtr as the substitution model. I can select it using the dropdown menu, but when I try to navigate to another tab, I get the following error message:

![2018-07-24-132314_2880x1024_scrot](https://user-images.githubusercontent.com/23251453/43155241-da322664-8f44-11e8-8ae7-e4cc36596f1c.png)

**Comment by GuyBaele** [comment]
I have tested this on my Linux machine using the latest BEAUti build from source and I'm unable to reproduce this error. So a new release of the software binaries should fix this problem. In the mean time, building a BEAST and/or BEAUti jar from the source code will have to do as a workaround.
