### ISSUE TITLE
ScaleOperator doesn't work on strictly negative parameters

### ISSUE THREAD

**Issue by mdhall272** [beast-dev/beast-mcmc#1009]
Discussed at https://github.com/beast-dev/beast-mcmc/commit/c7b873cb26a562df4c2a55c882c92464345cfcdf - I cannot find a way to get a ScaleOperator to work on a negative parameter, which is a reasonable thing to want to do. If the parameter has an upper bound of zero then the XML fails to parse:

`Error parsing '<scaleOperator>' element with id, 'null':
Scale operator can't be used on parameters with a finite upper bound (use a RandomWalk) (exponential.popSize)`

A workaround of making a NegativeStatistic to represent the desired parameter value and having ScaleOperator work on the positive version does not work as many parsers expect a Parameter and won't settle for a Statistic.

A couple of examples (with the wrong file extensions since GitHub won't let me upload XML):

[scaleOperatorDemo.txt](https://github.com/beast-dev/beast-mcmc/files/2227779/scaleOperatorDemo.txt)
[scaleOperatorDemo2.txt](https://github.com/beast-dev/beast-mcmc/files/2227780/scaleOperatorDemo2.txt)

(Quite happy to fix this myself if no objections are raised!)

**Comment by plemey** [comment]
What about using a productParameter, with one of the inner parameters fixed to  -1 and operating on the other?

**Comment by mdhall272** [comment]
Sure, that would work, but is this a hoop that the user should need to jump through? Perhaps it's rare enough not to worry about?

**Comment by rambaut** [comment]
I have no problem with a scale operator on a parameter that is strictly negative but then perhaps the user didn't mean to have a negative starting value. So perhaps if the starting value is negative and the upper="0.0" then this should be accommodated.

**Comment by rambaut** [comment]
Please feel free to implement that condition if you think it reasonable.

**Comment by mdhall272** [comment]
It seems like from the current code you cannot initialise a ScaleOperator unless the Parameter has a lower bound of 0 (even not specifying the lower bound does not work). I have changed this to look to the starting value for guidance.
