### ISSUE TITLE
One xml file runs from BEAST gui, but cannot be parsed on the command-line

### ISSUE THREAD

**Issue by moskalenko** [beast-dev/beast-mcmc#1013]
Why would BEAST run an input xml file generated by beauti from beast-1.10.0 when a run is started from the BEAST Java gui, but fail when run on the command-line with the following error?

SEVERE: Parsing error - poorly formed BEAST file, test.xml:
The '<codonPartitionedRobustCounting>' element, with id, 'all_vc_final_codon_aln_062218.robustCounting1', is incorrectly constructed.
The following was expected:
Exactly one ELEMENT of name firstPosition REQUIRED containing
    Exactly one ELEMENT of type AncestralStateBeagleTreeLikelihood REQUIRED

Error thrown at: dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)

This error does not show up if -beagle_instances argument is omitted.

**Comment by rambaut** [comment]
Insufficient information to replicate. Likely to do with `-beagle_instances` which has had some recent attention so is likely no longer an issue.
