### ISSUE TITLE
allMus with unequal weights clashes with Dirichlet prior

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#1021]
For example, the Ebola data set has 4 weights in total, with the weight for the intergenic region partition differing from the 3 weights of the codon positions. A deltaExchange combined with a Dirichlet prior (which we have been suggesting as of late) rejects all changes to ig.mu, given its different weight from the other positions (see screenshot). 

![screen shot 2018-09-02 at 20 51 13](https://user-images.githubusercontent.com/1092968/44959763-54a2aa80-aef4-11e8-9903-211a5a9ee430.png)

The easiest way to fix this or make it more robust could be to simply use equal weights for all partitions, which in this case eliminates the problem:

![screen shot 2018-09-02 at 21 12 32](https://user-images.githubusercontent.com/1092968/44959798-f1654800-aef4-11e8-848d-c876131ba314.png)

**Comment by maxbiostat** [comment]
I thought we switched to the `mu` parametrisation exactly to escape DeltaExchange with unequal weights. What am I missing?

**Comment by rambaut** [comment]
Yes. Dirichlet can only be used if the delta exchange has equal weights. Which means it can't be used on unequal sized partitions. Hence the switch to _nu_s which have been adjust for the partition size and thus can use an equal delta exchange. But the logger rescales these back to _mu_s for easy interpretation.

**Comment by GuyBaele** [comment]
So I assume we keep things as they are for now, and eventually get rid of the 'return to classic priors' checkbox?

**Comment by rambaut** [comment]
Yes. But perhaps we should throw a parser error to help clarify this.

**Comment by rambaut** [comment]
Got rid of classic prior option
