### ISSUE TITLE
log both allNus and allMus?

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#1022]
Using the new parameterization, we're operating on the 'allNus' but still logging the 'allMus' which is kind of strange to me. Additionally, this leaves me puzzled as to how generalized stepping-stone sampling should work? Ideally, I'd like to construct working priors using the 'allNus', so that would mean logging them. Is it out of the question to log both?

**Comment by maxbiostat** [comment]
The mu's are of direct scientific interest, since they are the relative weights of the evolutionary rate. The nu's are merely a computational trick that supposedly make sampling more efficient.

**Comment by rambaut** [comment]
No reason why we couldn't log _nu_s as well as _mu_s.

**Comment by maxbiostat** [comment]
Yeah, but logging the nu's serves no purpose to the end user, unless they're interested in the detecting mixing problems. My understanding is that the mus are just a computational trick; they're hard to interpret. Maybe best to avoid confusion and just log the mus.

**Comment by rambaut** [comment]
Didn't mean to close it.

**Comment by GuyBaele** [comment]
Logging both for the moment.
