### ISSUE TITLE
Error creating 'nu' parameter with Amino Acid model?

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#1023]
I'm using BEAST v1.10.1, and have received the following error: 

Creating site rate model.

Creating site rate model.

Creating site rate model.

Creating site rate model.

Creating site rate model.

Creating site rate model.

Creating site rate model.
Sep 04, 2018 1:47:38 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, NEXTEST.xml:
Object with idref=B62.nu has not been previously declared.

Error thrown at: dr.xml.XMLParser.convert(Unknown Source) 

My data is partitioned based on the substitution model I want to apply, so B62 is my Blosum 62 partition. The .nu suggests this is something to do with the allNus parameter, but I'm not sure what to do about it. The only mention of B62.nu in my XML is as follows: 

    
    <compoundParameter id="allNus">
        <parameter idref="B62.nu"/>
        <parameter idref="CPR.nu"/>
        <parameter idref="DHF.nu"/>
        <parameter idref="FLU.nu"/>
        <parameter idref="JTT.nu"/>
        <parameter idref="LGM.nu"/>
        <parameter idref="WAG.nu"/>
    </compoundParameter>

Should it be declared somewhere earlier in my XML? Any suggestions would be massively appreciated. Thank you!

**Comment by GuyBaele** [comment]
The siteModel indeed does not contain any ```nu``` parameter when generated by BEAUti, and looks like this when I try it:

<siteModel id="AA_test.siteModel">
		<substitutionModel>
			<aminoAcidModel idref="AA_test.aa"/>
		</substitutionModel>
	</siteModel>

Obviously, this then fails when the compoundParameter is being created:

<compoundParameter id="allNus">
		<parameter idref="AA_test.nu"/>
		<parameter idref="BB_test.nu"/>
	</compoundParameter>

**Comment by GuyBaele** [comment]
In the ```SubstitutionModelGenerator.writeAASiteModel```, ```parameter.getSubParameters().size()``` equals 0 and hence the relative rate block isn't generated. Will investigate later.

**Comment by zurkoe** [comment]
I am still facing this issues with BEAST 1.10.4

**Comment by anabut123** [comment]
Hi everybody,
Was this issue ever solved because I am having the same problem, with BEAST 1.10.4. 
Any help or suggestions would be much appreciated,
Ana

**Comment by rambaut** [comment]
Fixed in BEAST v10.5.0 beta 1
