### ISSUE TITLE
Unable to install BEAST.v1.10.1 / no mountable file systems Error

### ISSUE THREAD

**Issue by bnitm** [beast-dev/beast-mcmc#1024]
Hello, 
I downloaded the .dmg to install the latest BEAST on Mac and I get "no mountable file systems". Can't proceed from here. I tried various ways, including downloading from different pages, restarting and opening in Terminal. 

v1.8.4 is currently on the Mac. Could this prevent it from working?
Help would be greatly appreciated. Thank you!
Salaul

**Comment by rambaut** [comment]
This is not a general problem as for most people it seems to be fine. However, I have seen one other case of this in a workshop. It won't be because v1.8.4 is installed. It may be due to the .dmg signing?

**Comment by rambaut** [comment]
@bnitm If possible, follow the instructions on this page about mounting in the command line and then paste any errors that come up here:

https://deciphertools.com/blog/2017-10-02-no-mountable-file-systems/
