### ISSUE TITLE
BEAST v1.10.1.exe is not a valid Win32 application 

### ISSUE THREAD

**Issue by Jessie20182019** [beast-dev/beast-mcmc#1029]
Dear all, 
I download the zipped BEAST for windows. BEAuti, LogCombiner, TreeAnnotator are working well. Unfortunately, the BEAST v1.10.1.exe is not a valid Win32 application so I cannot open it. 
Have you ever encountered this? Any suggestions? Thank you for your help!

Regards,
Jess

**Comment by rambaut** [comment]
This will be regenerated to make v1.10.2 and will test it so will close this.
