### ISSUE TITLE
BEAUti prior dialog box won't open

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#1032]
I'm on Linux, using trunk and release BEAST. Steps to reproduce:
- Select skygrid as your tree prior;
- In the Priors tab, try to click the little box for skygrid.precision in order to change the hyperparameters on the Gamma prior
Result:
- the dialog box won't open.

**Comment by rambaut** [comment]
As it is currently implemented, the prior on the skygrid and skyride precisions are fixed. If this is the correct behaviour then the button should be visibly 'greyed out'. I am not sure about the rationale for now allowing other priors.

**Comment by rambaut** [comment]
You can adjust the gamma parameters but not change it to another prior type.
