### ISSUE TITLE
BEAUti-generated GLM analyses no longer run

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#1033]
The most recent change to BinomialLikelihoodParser generates the error below upon running a GLM XML file (generated by BEAUti). Additionally, older XML files with a GLM no longer run using the latest BEAST version.

SEVERE: Parsing error - poorly formed BEAST file, Dengue997_s3_AMVN_Mus_GLM_avmvn.xml:
Error parsing '<binomialLikelihood>' element with id, 'null':
Trials dimension (1) must equal counts dimension (2)

Error thrown at: dr.inferencexml.distribution.BinomialLikelihoodParser.parseXMLObject(BinomialLikelihoodParser.java:86)

**Comment by rambaut** [comment]
Could you post the relevant XML snippits?

**Comment by GuyBaele** [comment]
The problem lies with parsing the following prior XML bit:


				<binomialLikelihood>
					<proportion>
						<parameter value="0.2928932188134524"/>
					</proportion>
					<trials>
						<parameter value="1.0"/>
					</trials>
					<counts>
						<parameter idref="location.coefIndicators"/>
					</counts>
				</binomialLikelihood>

Do you need me to e-mail you a full XML file?

**Comment by rambaut** [comment]
Yes. Please.

**Comment by rambaut** [comment]
I can see what the issue is but not what the correct behaviour should be just yet.
