### ISSUE TITLE
BEAUti doesn't allow shared clock model across partitions without overlapping taxa.

### ISSUE THREAD

**Issue by evogytis** [beast-dev/beast-mcmc#1045]
1. Load more than one sequence partition (with no taxa shared between them).
2. Select multiple partitions.
3. Link clock models.

Produces an "unsupported configuration" error that says "to share a clock model, partitions need to have identical taxa". It should be possible to have non-overlapping taxa under the same clock model, though perhaps not under the default CTMC reference prior.

**Comment by rambaut** [comment]
A clock model is specific to a tree (i.e., the rates per branch in a relaxed clock or local clock). To share the parameters of a clock between clock models then the parameters can be linked in the priors table (or use a hierarchical model).
