### ISSUE TITLE
File "beast-beagle.jar" appears to be missing from 1.10.4

### ISSUE THREAD

**Issue by petersmp** [beast-dev/beast-mcmc#1046]
I download the [1.10.4 tar ball](https://github.com/beast-dev/beast-mcmc/releases/download/v1.10.4/BEASTv1.10.4.tgz) for Linux and followed the installation instructions. I have also installed Beagle (in /usr/local/lib/ where it is found). Beauti runs fine, but Beast is failing with this error messages:

```
Unable to load CPU plugin!
Please check for proper libhmsbeagle installation.
```
and

```
Using BEAGLE TreeLikelihood
  Branch rate model used: discretizedBranchRates
Dec 18, 2018 9:22:04 AM beagle.BeagleFactory loadBeagleInstance
INFO:   BEAGLE function, create, returned error code -6 (No resource matches requirements)
Fatal exception: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
java.lang.RuntimeException: No acceptable BEAGLE library plugins found. Make sure that BEAGLE is properly installed or try changing resource requirements.
	at beagle.BeagleFactory.loadBeagleInstance(Unknown Source)
	at dr.evomodel.treelikelihood.BeagleTreeLikelihood.<init>(Unknown Source)
	at dr.evomodelxml.treelikelihood.BeagleTreeLikelihoodParser.createTreeLikelihood(Unknown Source)
	at dr.evomodelxml.treelikelihood.BeagleTreeLikelihoodParser.parseXMLObject(Unknown Source)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

```

However, it is finding the Beagle installation because I also get the notice (higher in the output):

```
Using BEAGLE library v3.1.2 for accelerated, parallel likelihood evaluation
2009-, BEAGLE Working Group - https://beagle-dev.github.io/
Citation: Ayres et al (2012) Systematic Biology 61: 170-173 | doi:10.1093/sysbio/syr100
```

Of note: before installing Beagle, I was getting a different error message.

Instead, this appears to be because the plugins are supposed to be generated from a file named "lib/beast-beagle.jar"  that is named in the classpath argument to java in the file "bin/beast"

The command to run beast (at the end of "bin/beast") is:

```
BEAST_LIB="$BEAST/lib"
java -Xms64m -Xmx15G -Djava.library.path="$BEAST_LIB:/usr/local/lib:$LD_LIBRARY_PATH" -cp "$BEAST_LIB/beast.jar:$BEAST_LIB/beast-beagle.jar" dr.app.beast.BeastMain $*
```

where `$BEAST` is defined in a long if block that appears to find the BEAST root. The file "lib/beast.jar" exists, but there is no file "lib/beast-beagle.jar"

I also tried building from source (using `ant` based on some google-code forum posts from 2010). It built, though in a different structure, but there is still no file named "beast-beagle.jar".

Am I doing something wrong, or was that file inadvertently left out of the distribution? I feel like I must be doing something wrong since this same structure (call to "lib/beast-beagle.jar" but only the "beast.jar" and "beauti.jar" files existing in "lib") has existed in every tar.gz release since 1.8.2. However, I cannot make heads or tails of this.

**Comment by rambaut** [comment]
`beast-beagle.jar` hasn't been used for many years. The reference to it in the shell script is silent residue of this and should be removed. That doesn't solve your issue - but I think that is probably a BEAGLE installation issue as BEAST is finding and calling BEAGLE fine - the error is an internal BEAGLE one.

**Comment by petersmp** [comment]
You are correct that it was a BEAGLE issue (I needed `export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH` -- I thought that I had done it, and I thought that it was included in the shell script). However, the error message that I got sent me in the wrong direction. It woud be great if that could be cleaned up.

Thanks
