### ISSUE TITLE
BEAuti creates empty AVMVN block

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#1048]
If you select the simplest possible model in BEAST and then toggle "adaptive mix", BEAUti will create an AVMVN block with no parameters in it:
```xml
<adaptableVarianceMultivariateNormalOperator weight="30" scaleFactor="1.0" initial="600" burnin="300" beta="0.05" coefficient="1.0" autoOptimize="true" formXtXInverse="false">
</adaptableVarianceMultivariateNormalOperator>
```
I think this would create many "empty" calls to an operator that does nothing. I haven't run an XML constructed this way, so I don't know if there'd be any other side effects.

**Comment by GuyBaele** [comment]
That should no longer happen with my latest commit. I assume this happened using isochronous sequences (otherwise the clock.rate should have ended up in AVMVN block)?

**Comment by maxbiostat** [comment]
Yes, precisely, isochronous sequences.

**Comment by GuyBaele** [comment]
Can you try again and let me know if this still occurs?
