### ISSUE TITLE
Missing states in log file

### ISSUE THREAD

**Issue by RHagenson** [beast-dev/beast-mcmc#1054]
Discovered upon running Tracer v1.7.1 on the .log output of BEAST v1.8.4 as installed via conda 4.6.8, state 43366000 of 200000000 was missing. 

What other details do you need from me to trace why this state might have been dropped from the .log output?

**Comment by rambaut** [comment]
Is it just that state missing? Is the whole line missing? Is the equivalent tree also missing?

**Comment by rambaut** [comment]
As a work around for this case, I suggest you just duplicate the line before.

**Comment by RHagenson** [comment]
Thank you for the workaround. I did just that in order to get my results read.

To answer your questions:

> Is it just that state missing?

Yes, it is only that state missing from the .log output. All other states are present.

> Is the whole line missing?

Yes, the whole line is missing.

> Is the equivalent tree also missing?

Yes, the tree is also missing.

**Comment by rambaut** [comment]
Is the drive the file is being written to on a network or in the machine running BEAST? Is it close to being full?

**Comment by RHagenson** [comment]
In the machine running BEAST, and it is not close to being full now, but the disk did run out of space at one time due to a concurrent job that writing to the same disk. Migrated the other job to write to a larger disk. I captured STDOUT and STDERR for the BEAST job. STDOUT has the state in it, STDERR has no output at all, let alone that the state might have been dropped due to write errors.

**Comment by rambaut** [comment]
It does sounds like a write error due to a full drive. At the moment these will be silent but it may be a good idea for BEAST to tell you there may be corruption in the log file. It would be handy to have a tool to clean these up afterwards.

**Comment by RHagenson** [comment]
Sounds good. I think logging an error to state a write error occurred would be helpful. Currently, I have no way of knowing if the full drive is why BEAST failed to output that state, but I think it is fair to say it did not help.

**Comment by rambaut** [comment]
The fact you had a full disk during the run makes me 99% sure that is what the issue was. BEAST doesn't generally drop states unless there is a disk issue or a network issue (if the drive is mounted on the network).

**Comment by RHagenson** [comment]
Sounds good. Thank you for your help!
