### ISSUE TITLE
Muse and Gaut (1994)

### ISSUE THREAD

**Issue by migrau** [beast-dev/beast-mcmc#1056]
How can I select the `Muse and Gaut (1994)` codon model? I can't find the option in the last version (1.10.4).
Thanks,

**Comment by plemey** [comment]
This is not implemented in BEAuti yet. Example xml can now be found in: https://github.com/beast-dev/beast-mcmc/tree/master/examples/CodonModels

**Comment by migrau** [comment]
Thanks, @plemey. So the only way by now is editing directly the xml, right?

**Comment by plemey** [comment]
At the moment, it indeed requires xml editing. However @rambaut has made this issue: https://github.com/beast-dev/beast-mcmc/issues/1057
So, may the next distribution will offer the BEAuti setup.
