### ISSUE TITLE
incorrect rescaling of starting tree with negative branch lengths

### ISSUE THREAD

**Issue by plemey** [beast-dev/beast-mcmc#1067]
When a starting tree is used with negative branch lengths, e.g. an MCC tree for which node heights set with mean heights, than BEAST rescales the tree even though tips were appropriately proportional to sampling time, which leads to a wrong offset for some of the tips. (e.g. first tree upon running attached xml with seed 666).
[eu_data_IR_sampled_geo_reconstruction_1.zip](https://github.com/beast-dev/beast-mcmc/files/3456744/eu_data_IR_sampled_geo_reconstruction_1.zip)

**Comment by plemey** [comment]
maybe an error should be thrown for starting trees with negative branch lengths?

**Comment by rambaut** [comment]
Disallows negative branch lengths.
