### ISSUE TITLE
problem assigning date uncertainty to taxa in BEAUti

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#1068]
There is a problem when assigning tip date uncertainty to taxa in the Tips panel in BEAUti, but only when you first sort the sequences (for example, according to their sampling dates). Steps to reproduce:
1. import data
2. parse sampling dates
3. sort according to date
4. select a few sequences and set their uncertainty
5. uncertainty will be assigned to different sequences than those that were selected

**Comment by rambaut** [comment]
Fixed
