### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ulfboge** [beast-dev/beast-mcmc#1069]
Dear beast-dev,
I am trying to run my own sequences on Beast (have downloaded the latest version) but keep getting the java.lang.NullPointerException. Everything works when I use the Beast-example files. What am I missing?
Best regards,
Johan
[beast_error.txt](https://github.com/beast-dev/beast-mcmc/files/3474271/beast_error.txt)
[12S_galag.txt](https://github.com/beast-dev/beast-mcmc/files/3474279/12S_galag.txt)

**Comment by alexeid** [comment]
Did you specify a node calibration? You are using a Calibrated Yule prior which requires and subset of taxa to be specified and a prior distribution on the MRCA of that subset. Unfortunately the error does not specify the line number and the method that is failing is rather long, so hard to tell from that error message exactly what is going wrong. But it is something to do with the calibrated tree prior not being specified correctly.

**Comment by ulfboge** [comment]
Dear Professor Drummond,

Thank you for your quick response! I did not specify a node calibration, thanks! It all runs smoothly now.

Best regards,
Johan

Från: Alexei Drummond <notifications@github.com>
Svara till: beast-dev/beast-mcmc <reply@reply.github.com>
Datum: onsdag 7 augusti 2019 00:44
Till: beast-dev/beast-mcmc <beast-mcmc@noreply.github.com>
Kopia: ulfboge <galago@live.se>, Author <author@noreply.github.com>
Ämne: Re: [beast-dev/beast-mcmc] java.lang.NullPointerException (#1069)

Did you specify a node calibration? You are using a Calibrated Yule prior which requires and subset of taxa to be specified and a prior distribution on the MRCA of that subset. Unfortunately the error does not specify the line number and the method that is failing is rather long, so hard to tell from that error message exactly what is going wrong. But it is something to do with the calibrated tree prior not being specified correctly.

**Comment by rambaut** [comment]
This issue seems to be sepecific to BEAST 2. I suggest it is moved to https://github.com/CompEvol/beast2 . Closing this here.
