### ISSUE TITLE
Threads and memory management in BEAST / BEAGLE

### ISSUE THREAD

**Issue by CelineReisser** [beast-dev/beast-mcmc#1070]
Hi,
We recently ran into a problem regarding the threads and memory management of BEAST on our cluster. We are trying to run BEAST on 56 CPUs. Despite trying to set the BEAST -threads and the BEAGLE -threads to the correct Numbers (e.g. 56), we always end up with a threading that is much too high  (8100+ threads), overloading the calculation node, while CPU usage in percent remains low.
We tried to set the two parameters to 1 (-threads 1 -beagle_thread_count 1), to "remove" parallelization, but we still end up with a usage of 66 threads.
Is there a thread control behaviour parameter we missed?

Have a good day.

Celine

**Comment by rambaut** [comment]
BEAGLE thread control was broken. `-beagle_thread_count` now correctly provides an upper cap on the number of threads that BEAGLE tries to create.
