### ISSUE TITLE
Input files preparation using bacterial whole genomes

### ISSUE THREAD

**Issue by darwinbandoy** [beast-dev/beast-mcmc#1080]
I tried reading all the tutorials however it always starts with the alignment already prepared.

Let's say I have 30 whole genome sequences of bacterial pathogens in fasta file, how do I generate the input files, what are the suggested alignment tools. 

Sorry if this is too basic but I tried searching online but I cannot find the answer.

**Comment by rambaut** [comment]
This site is for reporting issues and bugs in BEAST.
