### ISSUE TITLE
Premature codon position pattern filtering for robust counting when an entire alignment column is non-nucleotide.

### ISSUE THREAD

**Issue by evogytis** [beast-dev/beast-mcmc#1082]
1. Create an alignment with length not a multiple of 3 for a robust counting analysis.
2. Add padding (Ns or gaps will do) into alignment to bring sequences "into frame".
3. Whichever codon position partition received an entire column of Ns (or gaps) will get filtered out, leading to unequal codon partition lengths and generate the following error: "Codon-partitioned robust counting requires all partitions to have the same length. Make sure that partitions include all unique sites and do not strip gaps."

One solution of dealing with insertions or alternatively spliced coding sequences is to delete the extraneous nucleotides, though it would be more elegant to allow entirely ambiguous columns through and filter codons rather than alignment columns.

Note if you can't replicate the error as described it may happen if there's more than one consecutive column of Ns/gaps.

**Comment by msuchard** [comment]
@evogytis -- and `strip = "FALSE"` in your site pattern parser doesn't solve this?

**Comment by evogytis** [comment]
That fixed it, though it wasn't there by default. Thanks!
