### ISSUE TITLE
ASYMQUADModel parsing error

### ISSUE THREAD

**Issue by tjhaxton** [beast-dev/beast-mcmc#1084]
I am attempting to conduct coalescence analysis with BEAST v1.10 and BEAUti v1.10.4 using microsatellite genotypes for four fish populations and ran into an issue. I tried the same approach with the example microsatellite data and experienced the same problem:

BEAST has terminated with an error. Please select QUIT from the menu.
Jun 2, 2020 4:45:39 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, microsatellite_data.xml:
Object with idref=ASYMQUADModel has not been parsed.

Error thrown at: dr.xml.XMLParser.convert(Unknown Source)

[microsatellite_data.xml.txt](https://github.com/beast-dev/beast-mcmc/files/4719685/microsatellite_data.xml.txt)

Thanks for any advice

T.

**Comment by mostinn** [comment]
T,
Did you manage to solve the ASYMQUADModel issue?

Thanks in advance,
m

**Comment by tjhaxton** [comment]
I had to use the previous version as I could not get the new version to work.

T.

Tim Haxton
Aquatic Research and Monitoring Section
705-760-1774

**Comment by rambaut** [comment]
Microsatellite data is no longer supported in BEAUti and bugs in v1.10.4 will not be fixed.
