### ISSUE TITLE
Reconstructing ancestral change History by accomodating dates and locations info  

### ISSUE THREAD

**Issue by ISskandaR** [beast-dev/beast-mcmc#1093]
Hi dears,
I'm facing an issue in reconstructing ancestral history change, actually I'm trying to perform a phyolgeographic analysis with discrete traits according to < https://beast.community/workshop_discrete_diffusion > by accomodating dates and locations travels according to (https://beast.community/travel_history.html).
I customized the XML file as described in the above mentioned links  and I used the customized Beast version available at https://beast.community/tutorials/travel_history/files/beast_travel_history.jar .
Unfortunately even by strictly following the sample XML format available at https://beast.community/tutorials/travel_history/files/9seqs_travelHistory.xml 
(taking in account any differences in between the inputs ) I did not succeed ; 
after my best try I got the following message :

![93115396-11bb6600-f6bc-11ea-9d6c-58fcdf916997](https://user-images.githubusercontent.com/24584488/93192671-35c38980-f746-11ea-948c-07a3557447d2.png)

I'd appreciate any kind of support
Best regards

**Comment by plemey** [comment]
I cannot replicate this error with 9seqs_travelHistory.xml and beast_travel_history.jar. It is not clear to me whether you are experiencing the error with only your own data set or also with the example xml.

**Comment by ISskandaR** [comment]
Hi Dears,
Thanks for the attention, I solved it a couple of years ago and I forgot to share the troubleshoot
Basically to be correctly launched on my dataset with chosen config Beast needed a strict clock model, the relaxed one led to the error 
Still thanks and keep having a nice job
