### ISSUE TITLE
enable multi-GPU support?

### ISSUE THREAD

**Issue by biocyberman** [beast-dev/beast-mcmc#1107]
Hi
According to this [thread](https://groups.google.com/g/beast-users/c/D5uf5DD2EL4/m/mifH8aw4CgAJ?pli=1), beagle_instances is disabled for beast version after 1.8.4. I am interested in running the latest beast version (i.e. with adjustment for SARS-CoV-2) with multiple GPUs. So my question is, what is the issue that lead to disabling `beagle_instances`? I can spend time to fix the issue after I know pre-existing info around the issue.

**Comment by rambaut** [comment]
`-beagle_instances` option automatically split an alignment into multiple equal sized partitions. As the multi-partition options in BEAST/BEAGLE became more complex, this option was difficult to maintain. Manual splitting into partitions is possible.
