### ISSUE TITLE
WGS SNP data to infer TMRCA of different samples within the sample population 

### ISSUE THREAD

**Issue by OmonkeyGOD** [beast-dev/beast-mcmc#1122]
Hi,

I am trying to estimate the diverging times of samples from different sources using the WGS SNPs. All the samples are the same species. 

I am wondering if the SNAPP package can handle this scenario or the standard one is suitable for it?

Thank you very much!
Yue

**Comment by rambaut** [comment]
SNAPP is a package for BEAST2, an independent project.
