### ISSUE TITLE
Beauti: allow to select multiple partition models: subst, clock, tree

### ISSUE THREAD

**Issue by GoogleCodeExporter** [beast-dev/beast-mcmc#113]
```

Can't select multiple subst models in 'Site models' panel to make changes
to all models.
```

Original issue reported on code.google.com by `jhe...@gmail.com` on 17 Aug 2009 at 12:42

**Comment by rambaut** [comment]
This issue is dealt with by the 'clone' button implemented in these panels - will clone the settings from one partition to the others.
