### ISSUE TITLE
lost the records in log file and trees file

### ISSUE THREAD

**Issue by AJFeng** [beast-dev/beast-mcmc#1141]
I have hundreds of BEAST trees that need to generate. I wrote a python code with a for loop to call the java and BEAST for batch BEAST tree generating. However,  I set 30MSampling for the MCMC but many of my trees and log files only have parts of the records such as 22M or 16M. Does anyone have the same problem? I am running in the Win10 system.

**Comment by rambaut** [comment]
Likely an issue with the script or environment used to run BEAST. Not possible to replicate.
