### ISSUE TITLE
formatting tags and release please

### ISSUE THREAD

**Issue by starsareintherose** [beast-dev/beast-mcmc#1142]
Now the tags and release are quite messy. It's not easy for linux community or distribution package beast-mcmc

https://github.com/beast-dev/beast-mcmc/releases/tag/v1.10.5pre_thorney_v0.1.2
https://github.com/beast-dev/beast-mcmc/releases/tag/v1.10.5pre_persistence_summarizer_v0.1

better to use 1.10.41 1.10.4x for pre-release

**Comment by rambaut** [comment]
Any thing with the pre-release label should not be distributed and are for manual downloading only.

**Comment by starsareintherose** [comment]
But what about the lastest release's name, no one knows what's the version of this

**Comment by rambaut** [comment]
v1.10.4 is the 'latest' non-preview release. Have fixed this.

**Comment by starsareintherose** [comment]
Okay, thanks a lot
