### ISSUE TITLE
Beast 1.10.4 program error message  Total = - Infinity

### ISSUE THREAD

**Issue by luguohui1999** [beast-dev/beast-mcmc#1144]
When I run Beast1.10.4,  the program stops and the following information is displayed:  Could you help me to solve the problem?
Using BEAGLE resource 0: CPU
    with instance flags:  PRECISION_DOUBLE COMPUTATION_SYNCH EIGEN_REAL SCALING_MANUAL SCALERS_RAW VECTOR_SSE THREADING_CPP PROCESSOR_CPU FRAMEWORK_CPU
  Ignoring ambiguities in tree likelihood.
  With 62 unique site patterns.
  Using rescaling scheme : dynamic (rescaling every 100 evaluations, delay rescaling until first overflow)

Using TreeDataLikelihood
  Branch rate model used: discretizedBranchRates
Creating swap operator for parameter branchRates.categories (weight=10.0)
Parameter weights for delta exchange are: 657	925	559	751	551	740	1129	953	752	942	1456	
Optimization Schedule: default

Likelihood computation is using an auto sizing thread pool.

Creating the MCMC chain:
  chain length = 1000000
  operator adaption = true
  adaptation delayed for 10000 steps
WARNING: Likelihood component, null, created but not used in the MCMC
WARNING: Likelihood component, treeLikelihood, created but not used in the MCMC
Dec 20, 2022 5:08:52 PM dr.app.beast.BeastMain <init>
SEVERE: Error running file: Cco_2022_yule.xml
Dec 20, 2022 5:08:52 PM dr.app.beast.BeastMain <init>
SEVERE: The initial model is invalid because state has a zero probability.

If the log likelihood of the tree is -Inf, this may be because the
initial, random tree is so large that it has an extremely bad
likelihood which is being rounded to zero.

Alternatively, it may be that the product of starting mutation rate
and tree height is extremely small or extremely large. 

Finally, it may be that the initial state is incompatible with
one or more 'hard' constraints (on monophyly or bounds on parameter
values. This will result in Priors with zero probability.

The individual components of the posterior are as follows:
The initial posterior is zero: 
  CompoundLikelihood(compoundModel)=(
    BooleanLikelihood=0.0, 
    Truncated(tmrca(Cco))=-Inf, 
    LogNormal(accD_psaI.kappa)=-1.8654, 
    LogNormal(petA_psbE.kappa)=-1.8654, 
    Exponential(petA_psbE.alpha)=-0.3069, 
    LogNormal(petB_petD.kappa)=-1.8654, 
    Exponential(petB_petD.alpha)=-0.3069, 
    Gamma(psbA_TrnH_GUG.gtr.AC)=-3.184, 
    Gamma(psbA_TrnH_GUG.gtr.AG)=-3.1687, 
    Gamma(psbA_TrnH_GUG.gtr.AT)=-3.184, 
    Gamma(psbA_TrnH_GUG.gtr.CG)=-3.184, 
    Gamma(psbA_TrnH_GUG.gtr.GT)=-3.184, 
    Gamma(psbB_psbH.gtr.AC)=-3.184, 
    Gamma(psbB_psbH.gtr.AG)=-3.1687, 
    Gamma(psbB_psbH.gtr.AT)=-3.184, 
    Gamma(psbB_psbH.gtr.CG)=-3.184, 
    Gamma(psbB_psbH.gtr.GT)=-3.184, 
    Exponential(psbB_psbH.alpha)=-0.3069, 
    LogNormal(rpoC1_rpoB.kappa)=-1.8654, 
    Exponential(rpoC1_rpoB.alpha)=-0.3069, 
    Gamma(rps18_clpP.gtr.AC)=-3.184, 
    Gamma(rps18_clpP.gtr.AG)=-3.1687, 
    Gamma(rps18_clpP.gtr.AT)=-3.184, 
    Gamma(rps18_clpP.gtr.CG)=-3.184, 
    Gamma(rps18_clpP.gtr.GT)=-3.184, 
    Exponential(rps18_clpP.alpha)=-0.3069, 
    LogNormal(rps8_rpl16.kappa)=-1.8654, 
    Exponential(rps8_rpl16.alpha)=-0.3069, 
    LogNormal(trnK_UUU_rps16.kappa)=-1.8654, 
    Exponential(trnK_UUU_rps16.alpha)=-0.3069, 
    Gamma(trnL_UAA_trnF_GAA.gtr.AC)=-3.184, 
    Gamma(trnL_UAA_trnF_GAA.gtr.AG)=-3.1687, 
    Gamma(trnL_UAA_trnF_GAA.gtr.AT)=-3.184, 
    Gamma(trnL_UAA_trnF_GAA.gtr.CG)=-3.184, 
    Gamma(trnL_UAA_trnF_GAA.gtr.GT)=-3.184, 
    LogNormal(trnS_GCT_trnR_TCT.kappa)=-1.8654, 
    Exponential(trnS_GCT_trnR_TCT.alpha)=-0.3069, 
    Uniform(allMus)=-2532.8436, 
    Uniform(ucld.mean)=-230.2585, 
    Uniform(ucld.stdev)=-230.2585, 
    LogNormal(yule.birthRate)=-2.0385, 
    BirthDeathGernhard08Model/yule(treeModel)=-5777.2021, 
    DiscretizedBranchRates(discretizedBranchRates[branchRates])=-350.5621
    Total = -Infinity
  ), 
  CompoundLikelihood(compoundModel)=(
    TreeDataLikelihood(TreeDataLikelihood)=-15535.2854, 
    TreeDataLikelihood(TreeDataLikelihood)=-19994.3218, 
    TreeDataLikelihood(TreeDataLikelihood)=-12602.2418, 
    TreeDataLikelihood(TreeDataLikelihood)=-31677.2163, 
    TreeDataLikelihood(TreeDataLikelihood)=-12022.8554, 
    TreeDataLikelihood(TreeDataLikelihood)=-16168.4752, 
    TreeDataLikelihood(TreeDataLikelihood)=-25509.857, 
    TreeDataLikelihood(TreeDataLikelihood)=-20643.8731, 
    TreeDataLikelihood(TreeDataLikelihood)=-15803.3828, 
    TreeDataLikelihood(TreeDataLikelihood)=-46280.7862, 
    TreeDataLikelihood(TreeDataLikelihood)=-29191.6099
    Total = -245429.9050874092
  )
  Total = -Infinity
For more information go to <http://beast.community>.

**Comment by rambaut** [comment]
The initial tree is not compatible with the conditions of the prior for the TMRCA of Cco. Not a BEAST issue.
