### ISSUE TITLE
installation of releases beyond v1.10.4

### ISSUE THREAD

**Issue by cecileane** [beast-dev/beast-mcmc#1145]
I am assuming that the latest version is the best and ready for broad usage, but I can't find instructions to install it. The [documentation](https://beast.community/install_on_unix) only refers to v1.10.4, and to files that don't seem to exist in the latest version, like `bin/beast` and `lib/beauti.jar`.
I would love any hint to create the jar files (assuming that's what I need).
Thanks!

**Comment by GuyBaele** [comment]
Hi Cécile,

I think the best approach would be to `git clone` the beast-mcmc repository and try to build / install using `ant` (this can be easily done using the IntelliJ IDE, which I prefer, but also via command line).
For example:
git clone git@github.com:beast-dev/beast-mcmc.git
cd beast-mcmc
ant build.xml

Upon successfully building the application, the jar files will be located in beast-mcmc/build/dist

Best regards,
Guy

**Comment by cecileane** [comment]
Fantastic, thank you Guy!
`ant build.xml` failed for me, but `ant` worked (in case this is helpful to others). As you can see, ant is new to me.
Also, prior to building, I did `git checkout sars-cov-2-origins` to get a version that can easily be referenced in a paper.
Thank you!
