### ISSUE TITLE
Dummy check for unaligned sequences in alignment

### ISSUE THREAD

**Issue by rmcolq** [beast-dev/beast-mcmc#1152]
Apparently both BEAUTi and BEAST will run very happily when given unaligned sequences (and produce garbage output after N days).

Useful dummy check that the length of sequences in the input "alignment" are all the same length

**Comment by rambaut** [comment]
Good thought. I think this will only be for importing FASTA files - Nexus files are alignments by definition.

**Comment by rmcolq** [comment]
There are no longer 100 open issues! Speedy resolution

**Comment by rambaut** [comment]
Low hanging fruit...
