### ISSUE TITLE
java.lang.NoClassDefFoundError: org/netlib/blas/BLAS

### ISSUE THREAD

**Issue by jrom99** [beast-dev/beast-mcmc#1155]
Hello, I've tried running the second exercise in the tutorial <https://beast.community/workshop_influenza_phylodynamics>, but the program stops with the following error:
`java.lang.NoClassDefFoundError: org/netlib/blas/BLAS`

[beast_log.txt](https://github.com/beast-dev/beast-mcmc/files/12178797/beast_log.txt)
[NewYork.HA.2000-2003.xml.txt](https://github.com/beast-dev/beast-mcmc/files/12178827/NewYork.HA.2000-2003.xml.txt) (GitHub doesn't support `.xml` files)

OS: Ubuntu 23.04
BEAST version: BEAST v1.10.4 Prerelease #bc6cbd9, 2002-2018 (installed using apt)

**Comment by rambaut** [comment]
Going to close this as it is unlikely due to the code. I suggest trying installing and compiling BEAST directly from the Github repo.

**Comment by jrom99** [comment]
I don't know why, but the version available in the Ubuntu repo wouldn't pick that library. But downloading https://github.com/beast-dev/beast-mcmc/releases worked as expected.
