### ISSUE TITLE
BEAUti relative rate specification for partitions 

### ISSUE THREAD

**Issue by plemey** [beast-dev/beast-mcmc#1158]
It may be useful to be able to select relative rates for partitions, similar to codon position relative rates, in the Sites panel when multiple partitions have been loaded. This option should probably only be selectable when the clock models are not unlinked across the partitions.

**Comment by rambaut** [comment]
This is already done – if you unlink substitution models in the partition panel – nus and mus are added for each partition (and each codon position within if selected). If you unlink clock models or trees then it goes to independent rates.

If this is not what you mean, reopen the issue.
