### ISSUE TITLE
error when using ant

### ISSUE THREAD

**Issue by liamxg** [beast-dev/beast-mcmc#1159]
ant
Buildfile: /Users/simon/Desktop/0/1/group/beast-mcmc/build.xml

init:
     [echo] BEAST: /Users/simon/Desktop/0/1/group/beast-mcmc/build.xml

compile-all:
    [javac] Compiling 765 source files to /Users/simon/Desktop/0/1/group/beast-mcmc/build
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] warning: [options] source value 8 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 8 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/inference/multidimensionalscaling/NativeMDSSingleton.java:126: error: missing return statement
    [javac]     }
    [javac]     ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/inference/parallel/MPILikelihoodRunner.java:116: warning: [removal] finalize() in Object has been deprecated and marked for removal
    [javac] 	public void finalize() {
    [javac] 	            ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/oldevomodel/indel/NativeTreeLikelihood.java:141: warning: [removal] finalize() in Object has been deprecated and marked for removal
    [javac]     protected void finalize() throws Throwable {
    [javac]                    ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/oldevomodel/indel/NativeTreeLikelihood.java:146: warning: [removal] finalize() in Object has been deprecated and marked for removal
    [javac] 	super.finalize();
    [javac] 	     ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/oldevomodel/treelikelihood/AbstractLikelihoodCore.java:122: warning: [removal] finalize() in Object has been deprecated and marked for removal
    [javac]     public void finalize() throws java.lang.Throwable {
    [javac]                 ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/oldevomodel/treelikelihood/AbstractLikelihoodCore.java:123: warning: [removal] finalize() in Object has been deprecated and marked for removal
    [javac]         super.finalize();
    [javac]              ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/oldevomodel/treelikelihood/AdvancedTreeLikelihood.java:418: warning: [removal] Integer(int) in Integer has been deprecated and marked for removal
    [javac]                     (deltaTips.size() == 0 || deltaTips.contains(new Integer(node.getNumber())))) {
    [javac]                                                                  ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/oldevomodel/treelikelihood/ArbitraryPrecisionLikelihoodCore.java:121: warning: [removal] finalize() in Object has been deprecated and marked for removal
    [javac]     public void finalize() throws java.lang.Throwable {
    [javac]                 ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/oldevomodel/treelikelihood/ArbitraryPrecisionLikelihoodCore.java:122: warning: [removal] finalize() in Object has been deprecated and marked for removal
    [javac]         super.finalize();
    [javac]              ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/xml/UserInput.java:83: warning: [removal] Double(double) in Double has been deprecated and marked for removal
    [javac] 				return new Double(input.readDouble());
    [javac] 				       ^
    [javac] /Users/simon/Desktop/0/1/group/beast-mcmc/src/dr/xml/UserInput.java:121: warning: [removal] Integer(int) in Integer has been deprecated and marked for removal
    [javac] 				return new Integer(input.readInteger());
    [javac] 				       ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 14 warnings

BUILD FAILED
/Users/simon/Desktop/0/1/group/beast-mcmc/build.xml:78: Compile failed; see the compiler error output for details.

Total time: 6 seconds

**Comment by msuchard** [comment]
fixed.
