### ISSUE TITLE
can not be opened for pathSamplingAnalysis element

### ISSUE THREAD

**Issue by liamxg** [beast-dev/beast-mcmc#1165]
BEAST has terminated with an error. Please select QUIT from the menu.
Nov 28, 2023 6:07:53 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, Clade-II.ucln.constant.psss.xml:
Error parsing '<pathSamplingAnalysis>' element with id, 'null':
File '/Volumes/ZJJ 2/0/Clade-II.ucln.constant.psss.mle.log' can not be opened for pathSamplingAnalysis element.

Error thrown at: dr.inference.trace.PathSamplingAnalysis$1.parseXMLObject(Unknown Source)

**Comment by rambaut** [comment]
The quoted file possibly doesn't exist? Doesn't look like a BEAST code issue.
