### ISSUE TITLE
How to speed beast on linux with only CPU

### ISSUE THREAD

**Issue by rookie-wzy** [beast-dev/beast-mcmc#1166]
I'm sorry to bother you. I have a copy of the data on the Y chromosome, which has 920 individuals and 38,323 variants and only one partition with GTR+G. According to a search of the literature, the chain length need to run about 100 million times. The configuration on my linux system is as follows: there are 224 cpus in total. 
<img width="1400" alt="b457845fb5cb666b8863d344afd1810" src="https://github.com/beast-dev/beast-mcmc/assets/145535333/ffb02ef5-344b-4c5c-b0f7-9fb37a84a447">

But I found that running beast on linux system is very slow, I also looked up some methods on Google. I have tried the following parameters, 1) -threads 60 , 2) -beagle_sse -beagle_instances 60, 3）-threads 30 -beagle_instances 30 ,but they all took about 30 hours/ million states. That means I need four months. 

Can you give me some ideas to speed it up on linux systems. I have another question, can I run 10 results with 10 different seeds, and finally merge the log file and tree file with LogCombiner?

**Comment by rambaut** [comment]
This issue list is for reporting bugs. Please send questions about using BEAST to the mailing list.
