### ISSUE TITLE
ambiguities in 'constant site patterns'

### ISSUE THREAD

**Issue by plemey** [beast-dev/beast-mcmc#1170]
treat ambiguities in otherwise constant site patterns as the constant state as an approximation to speed up likelihood evaluation

**Comment by rambaut** [comment]
Implemented. Can be turned on in XML using `ambiguousConstant="true"` as an attribute in <patterns ...> or using the command line option `-pattern_compression ambiguous_constant` when running BEAST (which will overrule the XML).
