### ISSUE TITLE
Can't launch Beauti or BEAST 1.10.4 in ARM Mac

### ISSUE THREAD

**Issue by RicardoRH96** [beast-dev/beast-mcmc#1171]
I installed the JDK, JRE, but the Oracle Java is not allowed at my institution.
Currently running MacOS Sonoma, and I can't install the Apple distributed Java; when I try to open Beauti or BEAST, I get the 
<img width="418" alt="Screenshot 2024-03-13 at 11 22 02 AM" src="https://github.com/beast-dev/beast-mcmc/assets/87875949/2a189782-6c48-437d-8325-8ad2bacfffca">
But it works if I double-click and select show package contents, Contents > Resources > Java > beast.jar.
I also tried to use the linux version and execute it from the terminal, but Beauti does not save BEAST XMLs.

**Comment by RicardoRH96** [comment]
@liamxg 
I already tried updating Java, installing the apple distribution, installing JDK using homebrew, etc.
My institution does not allow the Oracle Distribution to be installed, so that's not an option.
Do you have a suggestion on how to make it work?

**Comment by RicardoRH96** [comment]
@rambaut

**Comment by rambaut** [comment]
We will be updating the packaging for the binary versions on Mac/Windows which hopefully will address this issue. It is difficult to check that it works with every OS/JVM combination.

**Comment by RicardoRH96** [comment]
Thank you Professor
