### ISSUE TITLE
Default to sampling uniformly from precision when parsing/importing dates with variable precisions in BEAuti

### ISSUE THREAD

**Issue by plemey** [beast-dev/beast-mcmc#1175]
It would be very useful to have BEAuti default to sampling uniformly from precision when parsing/importing dates with variable precisions. This was noted by a number of users who thought that the variable precision was accounted for when parsing it or simply forget to also select 'sampling uniformly from precision' as the 'Tip date sampling' option.

**Comment by rambaut** [comment]
Done.
