### ISSUE TITLE
Wrong path to logcombiner executable

### ISSUE THREAD

**Issue by pedrosenna** [beast-dev/beast-mcmc#1202]
I've installed the BEAST X v10.5.0-beta4 Prerelease #46f5180b7 yesterday and all programs but logcombiner would initialize properly. It took me some time but i found that the path to logcombiner within the shell script is incomplete.

### default path to logcombiner (does not work)
`java -Xms64m -Xmx2048m -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/beast.jar" dr.app.tools.LogCombiner $*
`
### fixed path (working)
`java -Xms64m -Xmx2048m -Djava.library.path="$BEAST_LIB" -cp "$BEAST_LIB/beast.jar" dr.app.tools.logcombiner.LogCombiner $*
`
Hope it gets fixed in the next releases.

**Comment by rambaut** [comment]
Thanks. Fixed now
