### ISSUE TITLE
Missing partition when generated with the "Create partition from trait" button in the "Traits" window

### ISSUE THREAD

**Issue by sdellicour** [beast-dev/beast-mcmc#1204]
I noticed a small issue in BEAUti: a new partition is not listed in the "Partitions" window when generated with the "Create partition from trait" button in the "Traits" window. Specifically, when the user is not creating a partition directly when importing external trait values (i.e. using the new window that pops up just after having imported trait values from an external file), at the moment it doesn't seem to be possible to create a partition later on using the "Create partition from trait" button.

A short video to illustrate this rather specific issue:
https://github.com/user-attachments/assets/885db041-d2e3-4bf2-88d3-193c97f5a3e9

Best,

Simon

**Comment by rambaut** [comment]
Fixed
