### ISSUE TITLE
bug in beauti v10.5.0-beta5 Skyride scaleFactor

### ISSUE THREAD

**Issue by evandiego83** [beast-dev/beast-mcmc#1212]
There appears to be a bug when using BEAUTI from the BEAST X v10.5.0-beta5 Prerelease #1d511b10c2. When specifying skyride you get the following error:
```
SEVERE: 
******
Error in input BEAST XML file, test.xml:
Error parsing '<gmrfBlockUpdateOperator>' element with id, 'null':
scaleFactor must be greater than or equal to 1.0

```

that is attributed to this: 
```
<gmrfBlockUpdateOperator scaleFactor="-1.0" weight="2">
			<gmrfSkyrideLikelihood idref="skyride"/>
```

**Comment by GuyBaele** [comment]
Thank you for reporting this, this has now been fixed in the source code.

**Comment by evandiego83** [comment]
thanks @GuyBaele for fixing this. A slightly naive question but how does one install from the source code as opposed to the downloads.
