### ISSUE TITLE
How to run the MPI version of BEAST?

### ISSUE THREAD

**Issue by darknigh** [beast-dev/beast-mcmc#123]
I saw there is a argument "-mpi", but when I use it, I get the error of "Can not access MPI". Then I download MPJ, and use mpjrun.sh to run the beast.jar, but I get the error of "uncognized argument: 0".
Can anyone tell me how to run the MPI version of BEAST? The performance of running BEAST in single node is not enough for me.

**Comment by msuchard** [comment]
Years ago, MPI was used for modest parallelization in the SMARTIE model only.  Since then, we have developed BEAGLE for substantially more efficient parallelization within BEAST.   An MPI-implementation of BEAGLE is planned for its next release.  Will keep you up-to-date.
