### ISSUE TITLE
Remove System.exit() calls

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#125]
... to facility scripting BEAST in non-OS environments like R, python, etc.

**Comment by rambaut** [comment]
Only System.exit() calls are in main() to return after CLI errors.

**Comment by msuchard** [comment]
Would like to use CLI from `R` via `RJava` to keep argument parsing (i.e. setting beagle, debug, etc.) consistent.  So, just need to restructure `main()` to have a single termination point.

**Comment by msuchard** [comment]
Can also use a JVM-wide trap to catch `System.exit()` as in `RBeastMain`.
