### ISSUE TITLE
BEAUTi: add JC in subsititution model

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#141]
Originally reported on Google Code with ID 132
```
There is previous code in BEAUTi, but JC was taken out.


```

Reported by `dong.w.xie` on 2009-08-26 04:06:57

**Comment by rambaut** [comment]
Jukes-Cantor is HKY with equal base frequencies and kappa fixed at 0.5. Could be set in BEAUti manually. Will investigate the complexity of putting the option in the drop down.

**Comment by rambaut** [comment]
Put it back in.
