### ISSUE TITLE
BEAUTi: tidy up the order in the log for better comparesion in Tracer 

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#152]
Originally reported on Google Code with ID 143
```
some of parameters are always in the log, they should be on the top first.
It will be convenient to compare same parameters between different logs. 

```

Reported by `dong.w.xie` on 2009-08-31 21:41:07

**Comment by rambaut** [comment]
Leaving this open - will add a 'meanRate' column to Strict Clock to allow for Tracer comparison.
