### ISSUE TITLE
BEAUTi: save current settings and use them for future analyses

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#159]
Originally reported on Google Code with ID 150
```
Where are the templates? How can we save our settings and use them for
future analyses? 


```

Reported by `dong.w.xie` on 2009-09-03 23:56:07

**Comment by rambaut** [comment]
BEAUti files can be saved and loaded (and the data changed).

A formal templating system has been created in the application 'BEASTGen'. http://beast.bio.ed.ac.uk/BEASTGen 

This is much more powerful than the old BEAUti template system. I am closing this issue but will start a new Enhancement request that BEAUti can generate a BEASTGen template.
