### ISSUE TITLE
Would be nice to have generic support for int,long,bool native internal BEAST parameter

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#162]
Originally reported on Google Code with ID 153
```

at code level, that is
```

Reported by `jheled` on 2009-09-05 20:30:27

**Comment by rambaut** [comment]
Not convinced about this. Might be a good idea for parameters to have flags as to their nature (positive, non-negative, integer, 0-1 etc) - these could be used to check that transition kernels and priors are appropriate.
