### ISSUE TITLE
Remove all rate node parameters from tree model

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#184]
Originally reported on Google Code with ID 175

```
Remove all rate node parameters from tree model, rate should be always
supported by branch rate model class.

```

Reported by `dong.w.xie` on 2009-09-24 04:16:36

**Comment by rambaut** [comment]
I agree this should be done (also the node traits in TreeModel). Models wanting to store traits on trees should use a TreeParameterModel. However there are two areas that would break: Firstly, the autocorrelated relaxed clock models which store rates on trees. This can readily be converted to use a BranchRateModel interface. Secondly ARGs seem to use them to store rate categories (not rates). This should be changed to use a TreeParameterModel<Integer> .

**Comment by rambaut** [comment]
Too much work to resolve this issue but have added @Deprecated to the methods
