### ISSUE TITLE
Label individual transition rate dimensions for CTM models in log files

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#304]

**Comment by msuchard** [comment]
Commit ddbcab75326505d9dae8df4a93078890be0a38c0 should implement this for SVSGeneral* and SVSComplex* models.  

@plemey needs to test before closing issue.

**Comment by plemey** [comment]
@msuchard 
This works perfectly for reversible models, but for nonreversible models an additional tweak might be useful. Currently the same rate label is assigned to rates with different directionality between a particular pair of states. For state A and B, both the rate for A to B and B to A get the label "rates.A.B". So, if there is a way to consistently keep the first state as origin state and the second as destination state, we could have "rates.A.B" and "rates.B.A" instead.

**Comment by msuchard** [comment]
Commit e39d2b7b17c606bc12d44399669c35a50196cb35 should fix this issue.  Below is some example XML:

```
<?xml version="1.0" standalone="yes"?>
<beast>

    <generalDataType id="states">
		<state code="A"/>
		<state code="B"/>
		<state code="C"/>
	</generalDataType>

    <complexSubstitutionModel>
        <dataType idref="states"/>
        <frequencies>
            <frequencyModel normalize="true">
                <dataType idref="states"/>
                <frequencies>
                    <parameter value="0.33 0.33 0.33"/>
                </frequencies>
            </frequencyModel>
        </frequencies>
        <rates>
			<parameter id="rates" value="1 2 3 4 5 6"/>
     	</rates>
     	<rateIndicator>
			<parameter id="indicators" value="6 5 4 3 2 1"/>
     	</rateIndicator>
    </complexSubstitutionModel>

	<report>
		<parameter idref="rates"/>
		<parameter idref="indicators"/>
	</report>

</beast>
```

@plemey, if this fixes your problem, then please close this issue.   Otherwise, send me an example XML and I'll get to the bottom of the problem.

**Comment by plemey** [comment]
cool, all done and closing
