### ISSUE TITLE
On line tutorials need refreshing

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#665]
Originally reported on Google Code with ID 658

```
Some of the tutorial on the wiki are getting a bit out of date (in particular describing
XML-level work for things that BEAUti can do).

Should be updated to include information about latest BEAUti:
Almost all the tutorials in 'Advanced Tutorials' and many in 'Phylogeography'. I suggest
explaining the BEAUti way and then describing the XML edits (i.e., keep what already
exists).

Corrupted:
http://beast.bio.ed.ac.uk/Summarizing_BEAST_trees

Empty:
http://beast.bio.ed.ac.uk/HPMs
```

Reported by `rambaut` on 2012-08-17 08:51:33

**Comment by rambaut** [comment]
Can be done in https://github.com/beast-dev/doc

**Comment by walterxie** [comment]
@rambaut and @GuyBaele 
The BEAST tutorial page http://beast.bio.ed.ac.uk/tutorials is totally broken. All files are linked to http://beast-mcmc.googlecode.com/files/..., which has been deprecated. But I still kept the backups of several tutorials. Do you want them to be uploaded to beast-dev/doc?

Cheers,
Walter

**Comment by rambaut** [comment]
@walterxie --- We are about to make http://beast.community the documentation site for BEAST v1.x - beast.bio.ed.ac.uk will redirect to there. We also have updated tutorial packages to upload which we will host on github. But thanks for pointing this out.

**Comment by rambaut** [comment]
New tutorials on http://beast.community/
