### ISSUE TITLE
Relaxed clock default should be continuous? 

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#675]
Originally reported on Google Code with ID 668
```
I had a play around with BEAUTi recently and couldn't help but notice that discretized
branch rates is the default for relaxed clock models. Since we now have a proper continuous
implementation of the relaxed clock, would it be worthwhile changing that to the default?


At the very least, we should at least provide this as an option in BEAUTi

Also, would it be possible to implement the model averaging as an option in BEAUTi
in the near future? 
```

Reported by `Sibon.Li` on 2012-10-22 21:06:00

**Comment by rambaut** [comment]
Need to think about the relaxed clocks offered. Pushing this back to 1.9

**Comment by maxbiostat** [comment]
I find the BMA idea particularly useful, but we'd need to think about which distributions to "offer".

**Comment by rambaut** [comment]
Implemented in BEAUti with a checkbox to choose the option. Runs at a similar speed to the discretised version but the reality of that will be dependent on how well it mixes and the operator weights.
