### ISSUE TITLE
Concurrency issues when two threads access the same tree likelihood

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#717]
Originally reported on Google Code with ID 710

```
With DiscreteTraitBranchRateModel takes a tree likelihood to provide ancestral states.
This is called from another tree likelihood in a different thread which causes concurrency
issues. Need to sync on something. 
```

Reported by `rambaut` on 2013-11-14 15:16:24

**Comment by rambaut** [comment]
Been a while since we looked at this model. Might have been superseded by more recent developments.

**Comment by rambaut** [comment]
Reported 5 years ago. Haven't seen a concurrency issues recently. Will close unless until a specific case is reported.
