### ISSUE TITLE
Sum constraints for Dirichlet distribution

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#718]
Originally reported on Google Code with ID 711
```
DirichletDistribution does not currently check for a sum-to-one constraint.   Add optional
attribute to either check or implement a sum-to-X constraint.
```

Reported by `msuchard` on 2013-11-14 16:15:17

**Comment by GuyBaele** [comment]
Sum to X constraint was implemented in the mean time and returns -Inf for the logPdf() is this constraint is not met. Checks for sum to 1 by default and sum to X if optional boolean attribute has been provided and has been set to true.
