### ISSUE TITLE
Tracer not rescaling trace plot for multiple traces

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#724]
Originally reported on Google Code with ID 717

```
When the posterior of two or more analyses are compared, value of only one analysis
is shown (if the values are very different; e.g. -4000, -6000 and -8000).

```

Reported by `rambaut` on 2013-12-14 08:32:50

<hr>
- _Attachment: 截图3.png<br>![截图3.png](https://storage.googleapis.com/google-code-attachments/beast-mcmc/issue-717/comment-0/截图3.png)_

**Comment by rambaut** [comment]
This issue was moved to beast-dev/tracer#11
