### ISSUE TITLE
Patch for /trunk/build_coalsim.xml

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#737]
Originally reported on Google Code with ID 730
```
Additional includes necessary so that JAR file runs out-of-the-box.
```

Reported by `armanbilge` on 2014-03-26 01:04:58

<hr>
 * *Attachment: [build_coalsim.xml.patch](https://storage.googleapis.com/google-code-attachments/beast-mcmc/issue-730/comment-0/build_coalsim.xml.patch)*

**Comment by rambaut** [comment]
Applied
