### ISSUE TITLE
Skygrid can reject all moves on popoulation sizes

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#746]
Originally reported on Google Code with ID 739

```
The attached XML file is an example with seed 1404212110396 (Mac, latest BEAST development
build, Beagle 2.0). This will run for 50,000,000 states without apparently changing
any population size at all following state 5000. It's not universal and the file runs
fine for other seeds (e.g. 1). The problem seems to be that after a few states the
Hastings ratios are always tiny (at least e^-25 and usually much smaller). 
```

Reported by `mdhall272` on 2014-07-01 13:57:23

<hr>
- _Attachment: [unif_sampCounts_2c_skygrid.xml](https://storage.googleapis.com/google-code-attachments/beast-mcmc/issue-739/comment-0/unif_sampCounts_2c_skygrid.xml)_

**Comment by rambaut** [comment]
The proximal cause is that GMRFMultilocusSkyrideBlockUpdateOperator is returning vanishingly small hastings ratio (log values on the order of -100).

**Comment by rambaut** [comment]
This needs fixing. The Newton-Raphson errors were revealed when we stopped just short-circuiting the move if there was a numerical error (by rejecting). Issue #899 provides a simple quickly occurring example of the N-R error. I am closing this to defer to #899.
