### ISSUE TITLE
Tracer 1.6 has option for categorical data but still won't load non-numerical trace files

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#760]
Originally reported on Google Code with ID 753

```
For example, the attached.
```

Reported by `mdhall272` on 2014-12-09 17:26:05

<hr>
- _Attachment: [wcc_X_9_fixedP_5.net.txt](https://storage.googleapis.com/google-code-attachments/beast-mcmc/issue-753/comment-0/wcc_X_9_fixedP_5.net.txt)_

**Comment by rambaut** [comment]
This issue was moved to beast-dev/tracer#10
