### ISSUE TITLE
Tracer BSP plots missing 10^-1 labels

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#766]
Originally reported on Google Code with ID 761
```
I was using Bayesian skyline plot to inferred demographic historie. I noticed
that there is no 10^-1 value on Y axis (please find attached file), also in
analysis of others, e.g. Moncrief et al. 2012 General lack of phylogeographic
structure in two sympatric, forest obligate squirrels (Sciurus niger and S.
carolinensis). 
```

Reported by `rambaut` on 2015-03-30 07:59:45

**Comment by rambaut** [comment]
Was an error in NumberFormatter (a hand-crafted number to string formatter). When s.f. was set to zero, it should switch to scientific notation but wasn't for 0.1 (which then got rounded to 0).
