### ISSUE TITLE
BEAuti: add selectable saveCompleteHistory="true" option for Renaissance Counting in BEAuti

### ISSUE THREAD

**Issue by plemey** [beast-dev/beast-mcmc#778]
By adding saveCompleteHistory="true" to the (two) codonPartitionedRobustCounting elements, trees will be annotated with full N and S histories for each branch. This allows summarising any N/S quantity from the trees: by site, by branch, by time..., but the annotation can be very rich, so it would better to have this as a selectable option for the renaissance counting selection in BEAuti.

**Comment by rambaut** [comment]
Implemented as checkbox
