### ISSUE TITLE
Ancestral sequence reconstruction broken with <mergePatterns> elements

### ISSUE THREAD

**Issue by twoseventwo** [beast-dev/beast-mcmc#779]
If you set up an XML in BEAUTi with partitions whose patterns elements are then merged (e.g. SRD06) and ancestral state reconstruction for the nucleotide codes (see attached), you get a meaningless short string of nucleotides for the reconstructed CP1+2 sequence. This is because the reconstruction is done on the set of unique patterns, rather than the full sequence. While ancestral state reconstruction should turn pattern compression off so each position can be reconstructed individually, the mergePatterns element appears to turn it on again.

[Dengue4.env.xml.txt](https://github.com/beast-dev/beast-mcmc/files/28880/Dengue4.env.xml.txt)

**Comment by rambaut** [comment]
The mergePatterns class doesn't keep the order of the patterns so it would be difficult to reconstruct the sequence. I think the easiest solution is to disallow ancestral reconstruction for mergedPatterns in BEAUti and check for this in BEAST.

**Comment by rambaut** [comment]
Fixed this as a bug by preventing BEAUti from selecting ancestral reconstruction for 1+2,3 codon position partitioning. Also put parser check for AncestralStateTreeLikelihood and MarkovJumpTreeLikelihood that prevents them from taking pattern lists with compressed (unique="true") patterns. Closing this issue but will create new one as an 'enhancement' to enable this in future.

**Comment by rambaut** [comment]
Removing the parser check as it is breaking some XMLs. Will add warning that ancestral reconstruction may be problematic.
