### ISSUE TITLE
BEAUti's MLE generation code creates a coalescentEventsStatistic even for non-coalescent tree models.

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#785]
```
<coalescentEventsStatistic>
	<speciationLikelihood idref="speciation"/>
</coalescentEventsStatistic>
```

Is this statistic required for MLE?

**Comment by GuyBaele** [comment]
This statistic is required for MLE using GSS for coalescent tree models. Will do some testing the next couple of days and commit a fix if necessary.

**Comment by rambaut** [comment]
CoalescentEventsStatisticParser requires a CoalescentIntervalProvider so this is simply a problem in BEAUti. The solution would be to disallow GSS for any tree prior where the likelihood class doesn't implement CoalescentIntervalProvider. Currently, the ones that do are GMRFSkyrideLikelihood  (skyride, skygrid), and the parameteric CoalescentLikelihood. At first pass this could be a check in the generate code (i.e., an error comes up at generation saying the options are not compatible).

**Comment by rambaut** [comment]
Implemented check as suggested above.
