### ISSUE TITLE
option for multiple runs

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#791]
@rambaut , as another feature request, I think it would be very nice if the user could tick a box in either BEAUti or BEAST to execute multiple runs of the same analysis (run_i would be appended to the file stem). It would be a nice way of "reminding" users they need to run their stuff with multiple seeds (starting points) to ensure proper convergence. Personally, it'd come in very handy for me, too.

**Comment by rambaut** [comment]
Marking this as closed as there is already a command-line option '-prefix' that will append a prefix to all log files. It might make sense to add this to the GUI dialog box (although the Mac binary only allows one instance to run at a time).

**Comment by necrolyte2** [comment]
Will `-prefix` prefix tree files(all files?) as well?
