### ISSUE TITLE
Cannot set a prior for "meanRate" and other priors "Indirectly specificed through other parameters" in BEAUTi

### ISSUE THREAD

**Issue by jonchang** [beast-dev/beast-mcmc#797]
[Advice on the mailing list suggests](https://groups.google.com/forum/#!topic/beast-users/YiGBZCFNWIc), when the overall rate is known for a relaxed clock model, to set the `meanRate` prior and leave the `ucld.mean` prior alone. However, this does not seem to be possible in BEAUTi.

Steps to reproduce (commit 7c3828286f on OS X)
1. Open BEAUTi and import `anolis.nex` from the `examples/Data` folder.
2. In the Clocks panel, select "Uncorrelated relaxed clock"
3. In the Priors panel, attempt to set the `meanRate` prior to a Uniform distribution

Expected behavior:
`meanRate` prior would be set and generated in the XML file

Actual behavior
`meanRate` prior remains unspecified and is not generated in the XML file

Note that it's still possible to manually edit the XML file to have the desired behavior.

**Comment by rambaut** [comment]
This behaviour was introduced since v1.8.0 (present in v1.8.2).

**Comment by rambaut** [comment]
Priors should be specified for actual parameters rather than indirectly computed properties. ucld.mean (or clock.rate) will now always appear in prior table but can be set as 'Fixed Value' if desired. Possibly should set Fixed Value as default if no calibrations (tip or node) exist.
