### ISSUE TITLE
location rates stop being updated

### ISSUE THREAD

**Issue by bramvrancken** [beast-dev/beast-mcmc#817]
I'm not at liberty to make the data public - but can privately share the xml. Summary of used models: asymmetric + BSSVS + Markov jumps, with 4 location states. 

The location rates are not updated any more after several millions of states. This happened at multiple replicates runs, e.g. at about state 18M with seed 1465893392786.

**Comment by maxbiostat** [comment]
which version of BEAST are you using, @bramvrancken ?

**Comment by bramvrancken** [comment]
this was with v1.8.3.

Bram


On 05 Jul 2016, at 14:09, Luiz Max F. Carvalho <notifications@github.com<mailto:notifications@github.com>> wrote:


which version of BEAST are you using, @bramvrancken<https://github.com/bramvrancken> ?

**Comment by maxbiostat** [comment]
v1.8.4 brought a couple bug fixes. Would it be possible to try again with the new [release](https://github.com/beast-dev/beast-mcmc/releases/tag/v1.8.4)?

**Comment by bramvrancken** [comment]
will try and post whether this solves the issue

B



On 05 Jul 2016, at 14:14, Luiz Max F. Carvalho <notifications@github.com<mailto:notifications@github.com>> wrote:


v1.8.4 brought a couple bug fixes. Would it be possible to try again with the new release<https://github.com/beast-dev/beast-mcmc/releases/tag/v1.8.4>?

**Comment by bramvrancken** [comment]
When I run with BEAST v1.8.4 with the seed it goes wrong with in v1.8.3 I get the following:

# BEAST v1.8.4
# Generated Tue Jul 05 20:25:07 CEST 2016 [seed=1465893392786]
# -overwrite -seed 1465893392786 BVloc2_r1.xml
state Posterior   Prior       Likelihood  rootHeight  ucld.mean   location.clock.rate location.nonZeroRates
0 -118074.5526 -4295.9173  -113778.6353 125.579     1E-3        1E-3        12.0000     -
Underflow calculating likelihood. Attempting a rescaling...
State 13: State was not correctly restored after reject step.
Likelihood before: -118062.856337504 Likelihood after: -118841.53449388636
Operator: allMus(windowsize=0.75) allMus


When I run with  v1.8.4 with a random seed it starts without error and runs for a few hours without problems:
# BEAST v1.8.4
# Generated Tue Jul 05 20:28:56 CEST 2016 [seed=1467743336036]
…
7425000 -46410.6210 -5686.1992  -40724.4219 114.361     1E-3        1.48613E-3  7.00000     0.31 hours/million states
7450000 -46463.2173 -5720.4973  -40742.7200 90.8206     1E-3        1.54076E-3  7.00000     0.31 hours/million states
7475000 -46408.7841 -5706.6186  -40702.1655 111.210     1E-3        1.97009E-3  7.00000     0.31 hours/million states

Hopefully this is informative?

Best,
Bram



On 05 Jul 2016, at 14:16, Bram Vrancken <u0030820@kuleuven.be<mailto:u0030820@kuleuven.be>> wrote:

will try and post whether this solves the issue

B



On 05 Jul 2016, at 14:14, Luiz Max F. Carvalho <notifications@github.com<mailto:notifications@github.com>> wrote:


v1.8.4 brought a couple bug fixes. Would it be possible to try again with the new release<https://github.com/beast-dev/beast-mcmc/releases/tag/v1.8.4>?

**Comment by rambaut** [comment]
Unclear if this is still an issue.

**Comment by GuyBaele** [comment]
Will ask Bram to re-test or send me the XML.

**Comment by GuyBaele** [comment]
Bram can't find the XML that produced this problem. Don't see any other option but to close this issue and wait to see if the problem resurfaces.
