### ISSUE TITLE
Add mechanism to provide citation for tip dated sampling ...

### ISSUE THREAD

**Issue by msuchard** [beast-dev/beast-mcmc#829]
... and other features that do not involve Citable objects.

**Comment by rambaut** [comment]
For tip dated sampling, TreeModel could be Citable and emit the citation if leaf parameters are created. But I agree there may be other cases where it is more about the composition of the overall model that needs cited. Could create parsers that simply return a Citable implementation which would then be put

there by BEAUti? Do we have an example?

**Comment by msuchard** [comment]
Starting a list of examples:

* Tip-date sampling (only operator/prior based)
* Fast dN/dS (Citable could be added to one of codon mapping classes)
* More to come ...

**Comment by msuchard** [comment]
All current examples add as of 1045935ba2d955e3ba0aa6c0a1d53d87f34e8c43
