### ISSUE TITLE
typo in HKY citation

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#836]
The citations [here](https://github.com/beast-dev/beast-mcmc/blob/931c91759cc61bba9a5e5aba5fc5f0c97b61f309/src/dr/evomodel/substmodel/nucleotide/HKY.java) and [here](https://github.com/beast-dev/beast-mcmc/blob/9d6ec218e23b6db16e8135eef70b6289f786866d/src/dr/oldevomodel/substmodel/HKY.java) misspell Hasegawa as "Hasegowa".

**Comment by GuyBaele** [comment]
Fixed.
