### ISSUE TITLE
BEAST sometimes chooses the same random number seed

### ISSUE THREAD

**Issue by pvanheus** [beast-dev/beast-mcmc#837]
BEAST jobs on our cluster sometimes end up with the same random number seed. This seems to happen when our schedule (SGE) starts multiple replicates of the same job at the same time on the same host. The behaviour might be related to the initialisation of MersenneTwisterFast() using currentTimeMillis().

(Observed with BEAST 1.8.1 and 1.8.3)

**Comment by GuyBaele** [comment]
Correct, but even initialising with nanoTime() for example might now solve this. From the Java documentation of currentTimeMillis(): 'Returns the current time in milliseconds. Note that while the unit of time of the return value is a millisecond, the granularity of the value depends on the underlying operating system and may be larger. For example, many operating systems measure time in units of tens of milliseconds.'

I typically simply insert a sleep() statement in my Linux job submission script, to ensure that no 2 replicates of a BEAST run end up with the same starting seed.

**Comment by rambaut** [comment]
Could include the process number in the seed but not sure if this will be available from java in all circumstances.

**Comment by pvanheus** [comment]
@rambaut I'm not sure why BEAST uses its own random number generator rather than java.security.SecureRandom (which gathers randomness from /dev/random and thus might block, but, in my testing for no more than about 20 seconds). In any event I get around the problem by, in the script that submits jobs on our cluster, gathering a seed from python's `random.SystemRandom()` which in turn relies in `/dev/urandom` which is about the best you can get on Linux if you want non-blocking randomness.

**Comment by rambaut** [comment]
We don't need cryptographic level randomness for MCMC, the RNG we use (MersenneTwister has good randomness properties). Most importantly we need the ability to start from a particular seed to replicate a run exactly.

**Comment by pvanheus** [comment]
@rambaut Ok, the MersenneTwister *does* look good for the given purposes. I think all RNGs I've encountered allow specification of a seed - I just didn't realise until we got unexpected results how the BEAST one is seeded. `random.SystemRandom()` could provide a useful seed if the seed is not user-specified.

**Comment by rambaut** [comment]
As you say, you could use it to get a seed for the MT RNG but looking at the JavaDoc, SecureRandom doesn't necessarily use /dev/random (depends on the Providers). If it doesn't then it is down to the seed again. For this issue, introducing a non-time dependent component to the seed would be sufficient. Process id does not have a cross-platform method. 

If submitting a batch of jobs, one could draw some random seeds from another RNG and specify each using -seed command line option for each job.

**Comment by pvanheus** [comment]
@rambaut "one could draw some random seeds from another RNG and specify each using -seed command line option for each job". This is, indeed, what I use:

    # this is used for -seed
    BEAST_SEED=`python -c 'from __future__ import print_function; import random; print(random.SystemRandom().randint(0, 9))'`

Python is guaranteed to use `/dev/urandom` for `random.SystemRandom()` on Linux.
