### ISSUE TITLE
Path sampling analysis on previously performed MLE's require both a fileName and a resultsFileName to be read into BEAST

### ISSUE THREAD

**Issue by mtolkoff** [beast-dev/beast-mcmc#844]
The first block of the XML file needs to read like this:

\<pathSamplingAnalysis fileName="MLE2-1.bsp.log" resultsFileName="MLE2-1.bsp.log"\>

in order to work. @GuyBaele is there a missing xor rule?

**Comment by GuyBaele** [comment]
The resultsFileName is not to be read, but to be written. This is where the resulting log marginal likelihood will be written to. But I'll make the attribute optional to ensure backwards compatibility.

**Comment by GuyBaele** [comment]
@mtolkoff : can you try again?

**Comment by mtolkoff** [comment]
I had to make the XML rule optional, but it works now.
