### ISSUE TITLE
Issue with BEAUTi Tips Import Dates

### ISSUE THREAD

**Issue by Azaxirus** [beast-dev/beast-mcmc#849]
BEAUTi 1.8.4
Under the Tips panel, there is a Import Dates function. I am trying to mass input date and taxon into BEAUTi. I have figured the dates but taxon is not working.
1. Is it possible to import Taxon?
2. What is the format the program looking for?
3. Is it a example for Import Dates that anyone can share?

Thanks

**Comment by rambaut** [comment]
It should be a tab-delimited text file with taxon name in first column and date in the second. Will test and add some information.

**Comment by rambaut** [comment]
Needs a column heading row:
taxon\tdate\r
tax1\t2015\r
.
.
