### ISSUE TITLE
Add model specific keywords into log headers to guide down-stream analysis

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#862]
The use of particular models or settings could result in keywords being inserted in to the comment headers at the top of trees and log files. This could be picked up by treeannotator and Tracer (for example to include phylogeographical reconstructions in the former and to give warnings about inappropriate demographic reconstructions in the latter).

**Comment by msuchard** [comment]
Doh ... such a great idea; why didn't you think of this sooner?

**Comment by plemey** [comment]
Indeed, might even be useful for treeAnnotator to pass some of these header comments to an MCC tree so that spreaD3 can pick up and use relevant info.

**Comment by rambaut** [comment]
Good idea. Could also propagate some of the other information in the log file headers such as when the analysis was run, what version of BEAST etc.

**Comment by rambaut** [comment]
Implemented: AbstractModel has addKeyword(String). If this is a likelihood then just add the keywords in the constructor. These will propagate through compound likelihood to the logger and then be printed in the header. Tree loggers will also find trait providers (i.e., branch rate models) and log their keywords too.
