### ISSUE TITLE
Implement Dirichlet prior for mu parameters.

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#872]
This will require new parameters \nu_i with \sum_{i=1}^n{\nu_i}=1 maintained by a deltaExchange. A Dirichlet(1,1) provides the prior. Then \mu_i = \nu_i L / l_i  where L is the total number of sites and l_i is the number of sites in partition i. For logging, we could either report \mu_i as before or the product of \mu_i and overall rate R.

**Comment by rambaut** [comment]
Implemented. Needs final testing and review.

**Comment by rambaut** [comment]
Leaving off by default. Keeping this issue open for checking for next version.

**Comment by GuyBaele** [comment]
Am currently running some tests related to this issue.

**Comment by GuyBaele** [comment]
Have performed a test run using the adaptive transition kernel without data to do moments checking for 10 nu_i and a Dirichlet prior that sums to 1.0, with all the alpha_i set to 1.0 (E[nu_i] = 0.1 and Var[nu_i] = 0.00818). This doesn't point to any issues (with the new parameterization nor with combining it with the adaptive transition kernel). 

<img width="1312" alt="momentschecking" src="https://user-images.githubusercontent.com/1092968/43603807-e92df26e-9648-11e8-9342-19ae6c2be7bb.png">

**Comment by GuyBaele** [comment]
Are the weights for the relative rate XML elements within siteModel (e.g. <relativeRate weight="13.639892904953147">) computed from the full/uncompressed partition lengths? Or from the unique site pattern counts per partition?
