### ISSUE TITLE
BEAUti fails when writing XML to file

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#880]
Loaded a data set from a BEAST XML file. Substitution model: HKY (basically default BEAUti settings). Leave everything else at default and try to write the XML file, I get:
Window title: 'The BEAST XML is incomplete'
Message: The BEAST XML is incomplete because: Substitution model or site model generation has failed: null

**Comment by rambaut** [comment]
Went away of its own accord.
