### ISSUE TITLE
Possible Bug?

### ISSUE THREAD

**Issue by edwinnjoto** [beast-dev/beast-mcmc#884]
BEAST v1.8.4, 2002-2016
       Bayesian Evolutionary Analysis Sampling Trees
                 Designed and developed by
   Alexei J. Drummond, Andrew Rambaut and Marc A. Suchard
                              
               Department of Computer Science
                   University of Auckland
                  alexei@cs.auckland.ac.nz
                              
             Institute of Evolutionary Biology
                  University of Edinburgh
                     a.rambaut@ed.ac.uk
                              
              David Geffen School of Medicine
           University of California, Los Angeles
                     msuchard@ucla.edu
                              
                Downloads, Help & Resources:
                 	http://beast.bio.ed.ac.uk
                              
Source code distributed under the GNU Lesser General Public License:
          	http://github.com/beast-dev/beast-mcmc
                              
                     BEAST developers:
	Alex Alekseyenko, Guy Baele, Trevor Bedford, Filip Bielejec, Erik Bloomquist, Matthew Hall,
	Joseph Heled, Sebastian Hoehna, Denise Kuehnert, Philippe Lemey, Wai Lok Sibon Li,
	Gerton Lunter, Sidney Markowitz, Vladimir Minin, Michael Defoin Platel,
          	Oliver Pybus, Chieh-Hsi Wu, Walter Xie
                              
                         Thanks to:
    	Roald Forsberg, Beth Shapiro and Korbinian Strimmer

Using BEAGLE library v2.1 for accelerated, parallel likelihood evaluation
2009-2013, BEAGLE Working Group - http://beagle-lib.googlecode.com/
Citation: Ayres et al (2012) Systematic Biology 61: 170-173 | doi:10.1093/sysbio/syr100

Random number seed: 1493967410306

Parsing XML file: NEW1_V3_Animal_try_constant_ucldmean_echo1000_log1000.xml
  File encoding: Cp1252
Looking for plugins in C:\Users\z5096787\Desktop\H5N1 Indonesia Project\Animal\7.Beast\New1\NEW1_V3_Animal_try_constant_ucldmean_echo1000_log1000\plugins
Read alignment: alignment
  Sequences = 164
      Sites = 1780
   Datatype = nucleotide
Site patterns 'patterns' created from positions 1-1780 of alignment 'alignment'
  unique pattern count = 386
Read attribute patterns, 'Locations.pattern' for attribute, Location
Creating the tree model, 'treeModel'
  initial tree topology = (((((((((((((((((((((((((((((((((EPI_ISL_134257_A/duck/Sukoharjo/BBVW-1428-9/2012_Duck_Sukoharjo_25/09/2012,EPI_ISL_134260_A/duck/Tegal/BBVW-1727-11/2012_Duck_Tegal_12/11/2012),(EPI_ISL_134259_A/duck/Sleman/BBVW-1463-10/2012_Duck_Sleman_04/10/2012,EPI_ISL_134262_A/duck/Blitar/BBVW-1731-11/2012_Duck_Blitar_13/11/2012)),((EPI_ISL_134258_A/duck/Bantul/BBVW-1443-9/2012_Duck_Bantul_03/08/2012,EPI_ISL_134266_A/muscovy_duck/Tegal/BBVW-1732-11/2012_Cairina_moschata_Tegal_13/11/2012),EPI_ISL_134261_A/duck/Wonogiri/BBVW-1730-11/2012_Duck_Wonogiri_13/11/2012)),EPI_ISL_167892_A/chicken/Bali/U8661/2009_Gallus_gallus_Bangli_13/05/2009),EPI_ISL_91447_A/chicken/Sleman/BBVW-71-231/2008_Chicken_Sleman_27/01/2008),EPI_ISL_91439_A/chicken/Sleman/BBVW-27-91/2008_Chicken_Sleman_11/01/2008),((EPI_ISL_91441_A/chicken/Sleman/BBVW-28-95/2008_Chicken_Sleman_22/01/2008,EPI_ISL_91544_A/duck/Sleman/BBVW-29-32185/2008_Duck_Sleman_15/01/2008),EPI_ISL_91530_A/duck/Magelang/BBVW-24-44380/2008_Duck_Magelang_15/01/2008)),EPI_ISL_91545_A/duck/Sleman/BBVW-29-32187/2008_Duck_Sleman_15/01/2008),EPI_ISL_91523_A/duck/Bantul/BBVW-78-22210/2008_Duck_Bantul_30/01/2008),EPI_ISL_91440_A/chicken/Sleman/BBVW-27-92/2008_Chicken_Sleman_13/01/2008),((EPI_ISL_91446_A/chicken/Sleman/BBVW-70-1083/2008_Chicken_Sleman_26/01/2008,EPI_ISL_91449_A/chicken/Sleman/BBVW-82-65/2008_Chicken_Sleman_26/01/2008),(EPI_ISL_91448_A/chicken/Sleman/BBVW-71-236/2008_Chicken_Sleman_27/01/2008,EPI_ISL_91546_A/duck/Sleman/BBVW-29-32189/2008_Duck_Sleman_15/01/2008))),EPI_ISL_91346_A/chicken/Badung/BBVD-219/2007_Chicken_Badung_23/05/2007),((EPI_ISL_91372_A/chicken/Denpasar/BBVD-145/2007_Chicken_Denpasar_27/03/2007,EPI_ISL_91514_A/duck/Bangli/BBVD-246/2007_Duck_Bangli_31/05/2007),EPI_ISL_91425_A/chicken/Magelang/BBVW-680-744/2007_Chicken_Magelang_21/09/2007)),EPI_ISL_91528_A/duck/Kulon_Progo/BBVW-618-11009/2007_Duck_Kulon_Progo_19/08/2007),(((EPI_ISL_91412_A/chicken/Kulon_Progo/BBVW-667-604/2007_Chicken_Kulon_Progo_22/09/2007,EPI_ISL_91534_A/duck/Magelang/BBVW-680-41042/2007_Duck_Magelang_21/09/2007),EPI_ISL_91362_A/chicken/Bantul/BBVW-446-24453/2007_Chicken_Bantul_12/07/2007),EPI_ISL_91375_A/chicken/Denpasar/BBVD-331/2007_Chicken_Denpasar_05/07/2007)),(EPI_ISL_91381_A/chicken/Denpasar/BBVD-560/2007_Chicken_Denpasar_17/09/2007,EPI_ISL_91426_A/chicken/Magelang/BBVW-680-74X/2007_Chicken_Magelang_21/09/2007)),((((EPI_ISL_91370_A/chicken/Bantul/BBVW-678-443/2007_Chicken_Bantul_21/09/2007,EPI_ISL_91539_A/duck/Magelang/BBVW-680-41051/2007_Duck_Magelang_21/09/2007),EPI_ISL_91373_A/chicken/Denpasar/BBVD-182/2007_Chicken_Denpasar_29/05/2007),EPI_ISL_91358_A/chicken/Bangli/BBVD-562/2007_Chicken_Bangli_18/09/2007),EPI_ISL_91418_A/chicken/Kulon_Progo/BBVW-855-633/2007_Chicken_Kulon_Progo_19/11/2007)),(((((EPI_ISL_91402_A/chicken/Klungkung/BBVD-484/2007_Chicken_Klungkung_23/08/2007,EPI_ISL_91443_A/chicken/Sleman/BBVW-626-233/2007_Chicken_Sleman_31/07/2007),EPI_ISL_91354_A/chicken/Bangli/BBVD-245/2007_Chicken_Bangli_31/05/2007),EPI_ISL_91368_A/chicken/Bantul/BBVW-627-23296/2007_Chicken_Bantul_28/08/2007),EPI_ISL_91409_A/chicken/Kulon_Progo/BBVW-610-11019/2007_Chicken_Kulon_Progo_19/08/2007),((EPI_ISL_91414_A/chicken/Kulon_Progo/BBVW-677-602/2007_Chicken_Kulon_Progo_19/09/2007,EPI_ISL_91444_A/chicken/Sleman/BBVW-626-234/2007_Chicken_Sleman_31/07/2007),EPI_ISL_91524_A/duck/Bantul/BBVW-949-2D362/2007_Duck_Bantul_02/12/2007))),(((((EPI_ISL_91345_A/chicken/Badung/BBVD-216/2007_Chicken_Badung_22/05/2007,EPI_ISL_91454_A/chicken/Tabanan/BBVD-461/2007_Chicken_Tabanan_18/08/2007),(EPI_ISL_91349_A/chicken/Badung/BBVD-302/2007_Chicken_Badung_20/06/2007,EPI_ISL_91537_A/duck/Magelang/BBVW-680-41047/2007_Duck_Magelang_21/09/2007)),((EPI_ISL_91356_A/chicken/Bangli/BBVD-387ab/2007_Chicken_Bangli_26/07/2007,EPI_ISL_91521_A/duck/Bantul/BBVW-678-24404/2007_Duck_Bantul_21/09/2007),EPI_ISL_91395_A/chicken/Jembrana/BBVD-298/2007_Chicken_Jembrana_18/06/2007)),EPI_ISL_91343_A/chicken/Badung/BBVD-175/2007_Chicken_Badung_02/05/2007),EPI_ISL_91408_A/chicken/Kulon_Progo/BBVW-537-11099/2007_Chicken_Kulon_Progo_02/08/2007)),(((((((((EPI_ISL_91359_A/chicken/Bangli/BBVD-563/2007_Chicken_Bangli_18/09/2007,EPI_ISL_91401_A/chicken/Klungkung/BBVD-455/2007_Chicken_Klungkung_21/08/2007),EPI_ISL_91422_A/chicken/Magelang/BBVW-662-763/2007_Chicken_Magelang_14/09/2007),EPI_ISL_91453_A/chicken/Tabanan/BBVD-339/2007_Chicken_Tabanan_10/07/2007),(((EPI_ISL_91538_A/duck/Magelang/BBVW-680-41050/2007_Duck_Magelang_21/09/2007,EPI_ISL_91553_A/duck/Sleman/BBVW-679-31024/2007_Duck_Sleman_21/09/2007),EPI_ISL_91407_A/chicken/Kulon_Progo/BBVW-453-11055/2007_Chicken_Kulon_Progo_12/07/2007),EPI_ISL_91549_A/duck/Sleman/BBVW-598-32237/2007_Duck_Sleman_15/05/2007)),((EPI_ISL_91369_A/chicken/Bantul/BBVW-678-441/2007_Chicken_Bantul_21/09/2007,EPI_ISL_91416_A/chicken/Kulon_Progo/BBVW-677-60X/2007_Chicken_Kulon_Progo_19/09/2007),EPI_ISL_91450_A/chicken/Tabanan/BBVD-107/2007_Chicken_Tabanan_09/03/2007)),((((EPI_ISL_91347_A/chicken/Badung/BBVD-277/2007_Chicken_Badung_11/06/2007,EPI_ISL_91352_A/chicken/Badung/BBVD-342/2007_Chicken_Badung_11/07/2007),EPI_ISL_91543_A/duck/Sleman/BBVW-1003-34368/2007_Duck_Sleman_16/12/2007),((EPI_ISL_91385_A/chicken/Gianyar/BBVD-687/2007_Chicken_Gianyar_26/12/2007,EPI_ISL_91442_A/chicken/Sleman/BBVW-493-214/2007_Chicken_Sleman_24/07/2007),EPI_ISL_91379_A/chicken/Denpasar/BBVD-494/2007_Chicken_Denpasar_27/08/2007)),EPI_ISL_91353_A/chicken/Badung/BBVD-532/2007_Chicken_Badung_03/09/2007)),(((EPI_ISL_91378_A/chicken/Denpasar/BBVD-456/2007_Chicken_Denpasar_21/08/2007,EPI_ISL_91517_A/duck/Bantul/BBVW-358-24381/2007_Duck_Bantul_19/06/2007),EPI_ISL_91413_A/chicken/Kulon_Progo/BBVW-667-605/2007_Chicken_Kulon_Progo_22/09/2007),(EPI_ISL_91423_A/chicken/Magelang/BBVW-662-764/2007_Chicken_Magelang_14/09/2007,EPI_ISL_91548_A/duck/Sleman/BBVW-598-32226/2007_Duck_Sleman_15/05/2007))),((((((EPI_ISL_91360_A/chicken/Bangli/BBVD-575/2007_Chicken_Bangli_25/09/2007,EPI_ISL_91410_A/chicken/Kulon_Progo/BBVW-610-11020/2007_Chicken_Kulon_Progo_19/08/2007),EPI_ISL_91344_A/chicken/Badung/BBVD-205/2007_Chicken_Badung_15/05/2007),((EPI_ISL_91380_A/chicken/Denpasar/BBVD-509/2007_Chicken_Denpasar_28/08/2007,EPI_ISL_91550_A/duck/Sleman/BBVW-599-33288/2007_Duck_Sleman_30/07/2007),(EPI_ISL_91518_A/duck/Bantul/BBVW-387-23310/2007_Duck_Bantul_25/06/2007,EPI_ISL_91547_A/duck/Sleman/BBVW-379-34423/2007_Duck_Sleman_24/07/2007))),EPI_ISL_91406_A/chicken/Kulon_Progo/BBVW-453-11054/2007_Chicken_Kulon_Progo_12/07/2007),EPI_ISL_91400_A/chicken/Klungkung/BBVD-417/2007_Chicken_Klungkung_06/08/2007),((EPI_ISL_91403_A/chicken/Kulon_Progo/BBVW-453-11051/2007_Chicken_Kulon_Progo_12/07/2007,EPI_ISL_91529_A/duck/Kulon_Progo/BBVW-950-13267/2007_Duck_Kulon_Progo_02/12/2007),EPI_ISL_91371_A/chicken/Buleleng/BBVD-545b/2007_Chicken_Buleleng_05/09/2007))),EPI_ISL_91424_A/chicken/Magelang/BBVW-667-944/2007_Chicken_Magelang_01/08/2007)),((((((((((((EPI_ISL_91415_A/chicken/Kulon_Progo/BBVW-677-603/2007_Chicken_Kulon_Progo_19/09/2007,EPI_ISL_91522_A/duck/Bantul/BBVW-678-2D403/2007_Duck_Bantul_21/09/2007),EPI_ISL_91452_A/chicken/Tabanan/BBVD-307/2007_Chicken_Tabanan_21/06/2007),(EPI_ISL_91405_A/chicken/Kulon_Progo/BBVW-453-11053/2007_Chicken_Kulon_Progo_12/07/2007,EPI_ISL_91411_A/chicken/Kulon_Progo/BBVW-667-601/2007_Chicken_Kulon_Progo_19/09/2007)),(EPI_ISL_91367_A/chicken/Bantul/BBVW-482-22235/2007_Chicken_Bantul_18/07/2007,EPI_ISL_91533_A/duck/Magelang/BBVW-680-41041/2007_Duck_Magelang_21/09/2007)),(EPI_ISL_91428_A/chicken/Magelang/BBVW-680-772/2007_Chicken_Magelang_21/09/2007,EPI_ISL_91551_A/duck/Sleman/BBVW-599-33289/2007_Duck_Sleman_30/07/2007)),EPI_ISL_91519_A/duck/Bantul/BBVW-387-23310x-1/2007_Duck_Bantul_25/06/2007),(((EPI_ISL_91357_A/chicken/Bangli/BBVD-555ab/2007_Chicken_Bangli_13/09/2007,EPI_ISL_91383_A/chicken/Gianyar/BBVD-429/2007_Chicken_Gianyar_15/08/2007),(EPI_ISL_91366_A/chicken/Bantul/BBVW-482-22234/2007_Chicken_Bantul_10/07/2007,EPI_ISL_91394_A/chicken/Jembrana/BBVD-273/2007_Chicken_Jembrana_08/06/2007)),EPI_ISL_91540_A/duck/Magelang/BBVW-680-41052/2007_Duck_Magelang_01/08/2007)),EPI_ISL_91516_A/duck/Bantul/BBVW-224-24466/2007_Duck_Bantul_05/05/2007),((EPI_ISL_91351_A/chicken/Badung/BBVD-328/2007_Chicken_Badung_03/07/2007,EPI_ISL_91427_A/chicken/Magelang/BBVW-680-771/2007_Chicken_Magelang_21/09/2007),EPI_ISL_91624_A/peaceful_dove/Denpasar/BBVD-480/2007_Other_avian_Denpasar_23/08/2007)),(((((((EPI_ISL_91531_A/duck/Magelang/BBVW-604-44401/2007_Duck_Magelang_28/05/2007,EPI_ISL_91552_A/duck/Sleman/BBVW-599-33290/2007_Duck_Sleman_30/07/2007),EPI_ISL_91451_A/chicken/Tabanan/BBVD-142/2007_Chicken_Tabanan_26/03/2007),(EPI_ISL_91419_A/chicken/Kulon_Progo/BBVW-922-511/2007_Chicken_Kulon_Progo_26/11/2007,EPI_ISL_91532_A/duck/Magelang/BBVW-604-44402/2007_Duck_Magelang_28/05/2007)),(EPI_ISL_91399_A/chicken/Klungkung/BBVD-279/2007_Chicken_Klungkung_12/06/2007,EPI_ISL_91445_A/chicken/Sleman/BBVW-663-55/2007_Chicken_Sleman_14/09/2007)),(((EPI_ISL_91429_A/chicken/Magelang/BBVW-680-773/2007_Chicken_Magelang_21/09/2007,EPI_ISL_91623_A/peaceful_dove/Badung/BBVD-493/2007_Other_avian_Badung_27/08/2007),EPI_ISL_91384_A/chicken/Gianyar/BBVD-458/2007_Chicken_Gianyar_21/08/2007),EPI_ISL_91361_A/chicken/Bantul/BBVW-446-24452/2007_Chicken_Bantul_12/07/2007)),((((EPI_ISL_91420_A/chicken/Magelang/BBVW-662-762/2007_Chicken_Magelang_14/09/2007,EPI_ISL_91527_A/duck/Kulon_Progo/BBVW-618-11003/2007_Duck_Kulon_Progo_19/08/2007),EPI_ISL_91526_A/duck/Kulon_Progo/BBVW-618-11001/2007_Duck_Kulon_Progo_19/08/2007),EPI_ISL_91365_A/chicken/Bantul/BBVW-482-22233/2007_Chicken_Bantul_18/07/2007),EPI_ISL_91382_A/chicken/Flores_Timur/BBVD-256/2007_Chicken_East_Flores_04/06/2007)),(((EPI_ISL_91350_A/chicken/Badung/BBVD-319ac/2007_Chicken_Badung_25/06/2007,EPI_ISL_91421_A/chicken/Magelang/BBVW-662-762A/2007_Chicken_Magelang_14/09/2007),(EPI_ISL_91535_A/duck/Magelang/BBVW-680-41043/2007_Duck_Magelang_21/09/2007,EPI_ISL_91536_A/duck/Magelang/BBVW-680-41044/2007_Duck_Magelang_21/09/2007)),(EPI_ISL_91376_A/chicken/Denpasar/BBVD-430/2007_Chicken_Denpasar_15/08/2007,EPI_ISL_91377_A/chicken/Denpasar/BBVD-435/2007_Chicken_Denpasar_16/08/2007)))),(((EPI_ISL_91398_A/chicken/Klungkung/BBVD-225/2007_Chicken_Klungkung_24/05/2007,EPI_ISL_91404_A/chicken/Kulon_Progo/BBVW-453-11052/2007_Chicken_Kulon_Progo_12/07/2007),EPI_ISL_91396_A/chicken/Jembrana/BBVD-298b/2007_Chicken_Jembrana_18/06/2007),(EPI_ISL_91515_A/duck/Bantul/BBVW-1005-24442/2007_Duck_Bantul_17/12/2007,EPI_ISL_91520_A/duck/Bantul/BBVW-387-23310x-2/2007_Duck_Bantul_25/06/2007))),(((EPI_ISL_91348_A/chicken/Badung/BBVD-288/2007_Chicken_Badung_13/06/2007,EPI_ISL_91355_A/chicken/Bangli/BBVD-343/2007_Chicken_Bangli_11/07/2007),EPI_ISL_91363_A/chicken/Bantul/BBVW-446-24454/2007_Chicken_Bantul_06/07/2007),(EPI_ISL_91374_A/chicken/Denpasar/BBVD-291/2007_Chicken_Denpasar_14/06/2007,EPI_ISL_91417_A/chicken/Kulon_Progo/BBVW-822-545/2007_Chicken_Kulon_Progo_04/11/2007)))),EPI_ISL_13342_A/Chicken/West_Java/TASIK1/2006_Chicken_Tasikmalaya_24/05/2006),(EPI_ISL_64080_A/Chicken/West_Java/TASIKSOL/2006_Chicken_Bandung_26/07/2006,EPI_ISL_64213_A/Quail/Central_Java/SMRG/2006_Other_avian_Boyolali_19/02/2006)),EPI_ISL_13348_A/Chicken/West_Java/SMI-ENDRI2/2006_Chicken_Sukabumi_25/01/2006),EPI_ISL_13343_A/Chicken/Papua/TB15/2006_Chicken_Mimika_07/10/2006),EPI_ISL_64340_A/chicken/West_Java/SMI-CSLK-EB/2006_Chicken_Bekasi_06/08/2006),((EPI_ISL_64075_A/Chicken/West_Java/GARUT-MAY/2006_Chicken_Garut_01/08/2006,EPI_ISL_64076_A/Chicken/West_Java/HAMD/2006_Chicken_Sukabumi_13/02/2006),EPI_ISL_13341_A/Chicken/West_Java/TASIK2/2006_Chicken_Bandung_16/05/2006)),(((((EPI_ISL_190517_A/swine/Tabanan/061/2006_Swine_Tabanan_30/09/2006,EPI_ISL_64079_A/Chicken/West_Java/SMI-PAT/2006_Chicken_Sukabumi_20/03/2006),EPI_ISL_64341_A/chicken/West_Java/TASIKSOB/2006_Chicken_Garut_26/07/2006),(EPI_ISL_13349_A/Chicken/West_Java/SMI-ENDRI1/2006_Chicken_Sukabumi_31/01/2006,EPI_ISL_64174_A/Muscovy_Duck/Jakarta/HABWIN/2006_Duck_East_Jakarta_28/07/2006)),EPI_ISL_13345_A/Chicken/Papua/TA5/2006_Chicken_Mimika_07/10/2006),((EPI_ISL_13344_A/Chicken/Papua/TB1/2006_Chicken_Mimika_07/10/2006,EPI_ISL_91397_A/chicken/Jembrana/BBVD-300/2006_Chicken_Jembrana_04/08/2006),EPI_ISL_91364_A/chicken/Bantul/BBVW-446-24456/2007_Chicken_Bantul_12/07/2007))),EPI_ISL_64624_A/Chicken/Deli_Derdang/BBPVI/2005_Chicken_Deli_Serdang_23/09/2005),EPI_ISL_13283_A/Chicken/Langkat/BBPV1-576/2005_Chicken_Langkat_25/11/2005),(EPI_ISL_13294_A/Chicken/Medan/BPPV1-498/2005_Chicken_Medan_15/09/2005,EPI_ISL_190516_A/duck/Badung/03/2005_Duck_Badung_31/08/2005)),EPI_ISL_190515_A/chicken/Denpasar/02/2004_Chicken_Denpasar_30/06/2004),EPI_ISL_30636_A/chicken/East_Kalimantan/UT1035/2004_Chicken_East_Kotawaringin_27/01/2004)
  tree height = 9.466327809802012
Using discretized relaxed clock model.
  over sampling = 1
  parametric model = logNormalDistributionModel
   rate categories = 1
Using strict molecular clock model.
dr.xml.XMLParseException: Object with idref=CP1+2.mu has not been previously declared.
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
May 05, 2017 4:57:29 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, NEW1_V3_Animal_try_constant_ucldmean_echo1000_log1000.xml:
Object with idref=CP1+2.mu has not been previously declared.
java.lang.RuntimeException: Terminate
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
Creating state frequencies model 'frequencies': Using empirical frequencies from data = {0.35422, 0.18154, 0.22228, 0.24196}
Creating HKY substitution model. Initial kappa = 2.0
Creating site model: 
  with initial relative rate = 1.0
  4 category discrete gamma with initial shape = 0.5

BEAST has terminated with an error. Please select QUIT from the menu.

**Comment by edwinnjoto** [comment]
[github_NEW1_V3_Animal_try_constant_ucldmean_echo1000_log1000.txt](https://github.com/beast-dev/beast-mcmc/files/980658/github_NEW1_V3_Animal_try_constant_ucldmean_echo1000_log1000.txt)

Hi Luiz
Thanks for your reply. Here I attach the xml file in txt format
I use skygrid and lognormal as the ucldmean
BEAUti create the entire XML in its current form. I did not do any manual manipulation of the xml.
Looking forward to your thought.

Best regards,
Edwin

**Comment by rambaut** [comment]
This is a bug where, if you turn on codon positions and then turn it off again, it doesn't completely reset the options. I will enter this as a new issue with more explicit description. As a work around, try remaking the XML using BEAUti.
