### ISSUE TITLE
weird behaviour of the gmrfBlockUpdateOperator

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#888]
Running this  [file](https://github.com/beast-dev/beast-mcmc/files/1007644/denv4_skygridTest_v2.xml.txt) with `-seed 666` will lead to popSizes not being updated throughout the chain. 

I chose deliberately bad starting values for the (log) popSizes.

Here's some debug output from the one and only @GuyBaele :

```
&& Operator: gmrfBlockUpdateOperator
Time: 0
** Evaluate
Time: 0
** Move rejected: new score = -9.012757713568026E7, old score = -3855.8111985578525
coerceAcceptanceProbability false
```
basically a terrible proposal, or

```
&& Operator: gmrfBlockUpdateOperator
Time: 0
** Evaluate
Time: 0
** Move rejected: new score = -3846.7606374877605, old score = -3854.333640426559
coerceAcceptanceProbability false
```
which seems to be a great uphill move, but ends up being rejected. Some more output with log HR:

```
&& Operator: gmrfBlockUpdateOperator
Time: 3
** Evaluate
Time: 0
** Move rejected: new score = -14750.057443992177, old score = -16195.996480418926 (logr = -40745.05752105011)
```
major improvement on posterior, but terrible MH ratio.

**Comment by twoseventwo** [comment]
Related? https://github.com/beast-dev/beast-mcmc/issues/746

**Comment by maxbiostat** [comment]
@twoseventwo , very possibly. Thanks for spotting that!

**Comment by rambaut** [comment]
Whether this is a different manifestation of #899 needs to be investigated. It may be numerical problems computing the HR.

**Comment by rambaut** [comment]
Related to other issues
