### ISSUE TITLE
Possible bug in determining branch rates under local clock model

### ISSUE THREAD

**Issue by haydenm** [beast-dev/beast-mcmc#889]
Consider a clade with root _C_ that has a local clock, in which the stem branch above the clade is not included. It appears that the branches corresponding to the immediate children of _C_ inherit the same rate as that of _C_. I am not certain whether I am misunderstanding something or this is an issue.

The problem could arise [here](https://github.com/beast-dev/beast-mcmc/blob/a5febbaaf90439649b07a2fb0a7deff5fbb8c5b2/src/dr/evomodel/branchratemodel/LocalClockModel.java#L177). If the stem branch is not included in the model, then the node corresponding to _C_ will not be put into `nodeClockMap` by the call to [`setNodeClock(..)`](https://github.com/beast-dev/beast-mcmc/blob/a5febbaaf90439649b07a2fb0a7deff5fbb8c5b2/src/dr/evomodel/branchratemodel/LocalClockModel.java#L267) (because `stemProportion`, on that call, would have value `0`). Thus, `parentClock` will be null at [L171](https://github.com/beast-dev/beast-mcmc/blob/a5febbaaf90439649b07a2fb0a7deff5fbb8c5b2/src/dr/evomodel/branchratemodel/LocalClockModel.java#L171), which would (mistakenly) cause the conditional at [L177](https://github.com/beast-dev/beast-mcmc/blob/a5febbaaf90439649b07a2fb0a7deff5fbb8c5b2/src/dr/evomodel/branchratemodel/LocalClockModel.java#L177) to be true and set `stemProportion` to `0` at [L186](https://github.com/beast-dev/beast-mcmc/blob/a5febbaaf90439649b07a2fb0a7deff5fbb8c5b2/src/dr/evomodel/branchratemodel/LocalClockModel.java#L186). The returned value of `rate` would then be `parentRate`, which, in this case, is the global rate.

If this is indeed an issue, I would be happy to submit a PR.

**Comment by rambaut** [comment]
Thanks Hayden, this was indeed a bug - well spotted.
