### ISSUE TITLE
Test Dirichlet prior on GTR rates

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#906]
Simulate some sequences and check recovery of generating values - compare with old priors (gamma on relative rates).

**Comment by maxbiostat** [comment]
@rambaut  think we got this [here](https://github.com/beast-dev/doc/blob/master/notebooks/gtr_simulations.ipynb) now, right?

**Comment by maxbiostat** [comment]
@rambaut : flagging for closing
