### ISSUE TITLE
BEAUti fails to load Nexus file generated from XML by BEASTGen 1.0.2

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#922]
Steps to reproduce:
1. ./beastgen to_nexus.template carnivores.xml carnivores.nex
2. Open BEAUti, File > Import Data: carnivores.nex
3. BEAUti gives the following error message: Error parsing imported file: Expecting ';' after sequences data, has 'A' in line 67

Directly loading the carnivores.xml into BEAUti works fine though.

[carnivores.xml.zip](https://github.com/beast-dev/beast-mcmc/files/1200358/carnivores.xml.zip)

**Comment by rambaut** [comment]
I can replicate the issue but can't see anything wrong with the nexus file. Geneious also complains ('Cause: After 10869 bases, expected end of sequence but next base was C. Is sequence the wrong length?') so probably an issue with the Nexus file. Will look closer.

**Comment by rambaut** [comment]
Actually it is obvious. Sequence labels with spaces in them need to be surrounded by quotes. So need to fix this in BEASTGEN

**Comment by rambaut** [comment]
Changed template to:
```
#NEXUS

BEGIN DATA;
	DIMENSIONS NTAX=${taxon_count} NCHAR=${site_count};
	FORMAT MISSING=? GAP=- DATATYPE=DNA;
	MATRIX
<#list alignment.sequences as sequence>
"${sequence.taxon.id}"  ${sequence.data}
</#list>
	;
END;
```
