### ISSUE TITLE
frequencyModel references wrong patterns when using codon position partitioning

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#927]
Steps to reproduce (or at least how I get to this error):
1. Load multiple genes as separate partitions into BEAUti
2. Unlink substitution models and clock models
3. Set up HKY model with empirical frequences, among-site rate heterogeneity and codon position partitioning (1,2,3) for the first model
4. Clone the previous setting to all other genes
5. Generate XML (I did the same steps as 3 and 4 for the clock model and used HPMs but that shouldn't matter to reproduce the error)

The patterns in the XML get IDs: gene-1.CP1.patterns, gene-2.CP1.patterns, gene-3.CP1.patterns, ...
The frequencyModel within the HKY refers to IDs: gene-1.CP1.gene-1.patterns, gene-2.CP1.gene-2.patterns, gene-3.CP1.gene-3.patterns, ...

**Comment by rambaut** [comment]
For empirical frequences, calculate these from the entire alignment.
