### ISSUE TITLE
logNormalDistributionModel in an HPM not parsed correctly

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#929]
Construct a set of parameters (in my case kappa parameters across different partitions) and put an HPM with a lognormal distribution on those parameters. In the XML file, the HPM is parameterized using a logNormalDistribution with a mean and a precision, but upon running the XML, the logNormalDistributionModelParser throws the following error:

java.lang.NullPointerException
	at dr.inferencexml.distribution.LogNormalDistributionModelParser.parseXMLObject(LogNormalDistributionModelParser.java:81)
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(AbstractXMLObjectParser.java:136)
	at dr.xml.XMLParser.convert(XMLParser.java:325)
	at dr.xml.XMLParser.convert(XMLParser.java:296)
	at dr.xml.XMLParser.convert(XMLParser.java:296)
	at dr.xml.XMLParser.convert(XMLParser.java:296)
	at dr.xml.XMLParser.parse(XMLParser.java:175)
	at dr.app.beast.BeastMain.<init>(BeastMain.java:165)
	at dr.app.beast.BeastMain.main(BeastMain.java:805)

**Comment by rambaut** [comment]
Should switch to using 'mu' and 'precision'. Not sure why it gives a null pointer though.

**Comment by GuyBaele** [comment]
The meanInRealSpace attribute was found, but when the parser searches for stdev, it doesn't find it and asking for a child of an unfound node gives a NullPointerException.

But the Parser code seems to indicate that you either specify MEAN and STDEV or MU and SIGMA, yet BEAUti generates an HPM XML that has MEAN and PRECISION. So is this just a matter of the XML having been generated in a manner inconsistent with the new logNormalDistribution code?

It seems like adding stdevInRealSpace="false" to the XML could do the trick ...

**Comment by rambaut** [comment]
Basically, we are going to remove ‘meanInRealSpace’ attribute (and ‘stdevInRealSpace’) and specify the parameterization by which parameters are given. The allowed options are;

1) mean, stdev
2) mu, sigma
3) mu, precision

If ‘meanInRealSpace’ attribute is present then true means 1) and false means 2) (but the parameters will be called mean and strdev) - this is for backwards compatibility.

So BEAUti should generate ‘mu’ and ‘precision’. 

But the parser needs fixing to throw an XMLParserException if it doesn’t find stdev.
