### ISSUE TITLE
different prior on the 'half degrees of freedom' parameter in gamma relaxed random walk

### ISSUE THREAD

**Issue by plemey** [beast-dev/beast-mcmc#941]
This prior (exponential with mean 10) may prevent some bad behaviour observed for a witch's hat gamma:
				<gammaPrior shape="1" scale="10.0" offset="0.0">
					<parameter idref="location.halfDF"/>
				</gammaPrior>

**Comment by rambaut** [comment]
@plemey - want it to be default in BEAUti?
