### ISSUE TITLE
multivariate RRWs can perform badly using discretised branch rates, but work well using 'arbitrary' branch rates integration 

### ISSUE THREAD

**Issue by plemey** [beast-dev/beast-mcmc#944]
Since the WNV PNAS paper, I have been having difficulties reproducing the results under the gamma-RRW (which was the most flexible and 'best-fitting' model). The issue relates to the way we integrate out the RRW rates: in the original analysis we were using the 'arbitrary' branch rate integration, but we than moved forward with the standard discretised branch rate integration. However, the default approach (and also the quantile integration) result in bad behaviour (e.g. the halfDF parameter takes on terribly small values, the trait likelihood 'sticks' to 0, node locations are all over the place). This is less of an issue for more constrained RRWs, such as the cauchy-RRW, but I think we better go to back to 'arbitrary' branch rate integration for all RRWs.
![halfdf](https://user-images.githubusercontent.com/708314/29810424-06057fdc-8ca0-11e7-9fe7-dea767e5989c.png)
![traitlikelihood](https://user-images.githubusercontent.com/708314/29810430-0af5bc64-8ca0-11e7-8892-7531672ff529.png)

**Comment by rambaut** [comment]
@plemey - would be useful if you could provide an example XML - perhaps take the standard example, generate an XML in the current BEAUti and then edit it to use arbitrary rates.

**Comment by plemey** [comment]
@rambaut - sure, here are the RRW examples modified to use the arbitrary branch rates. (look for 
[RRWs.zip](https://github.com/beast-dev/beast-mcmc/files/1523891/RRWs.zip)

**Comment by rambaut** [comment]
Thanks. Will get this done.

**Comment by msuchard** [comment]
@Zhenyu028 is working on a great sampler for arbitrary rates on really large trees (but not for the 1.10 release).

**Comment by rambaut** [comment]
Awesome. Will have some great datasets to test it on.
