### ISSUE TITLE
Don't print initial tree in console preamble text

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#949]
It is boringly large for big datasets and is the first tree in the trees file anyway.

**Comment by msuchard** [comment]
If users want the tree printed, they can include a 
```
<report>
  <treeModel idref="treeModel"/> 
</report>
```
 in their XML.

**Comment by rambaut** [comment]
True.

**Comment by GuyBaele** [comment]
Have added Marc's suggestion to the FAQ on beast.community
