### ISSUE TITLE
GLM Model

### ISSUE THREAD

**Issue by antoine4ucsd** [beast-dev/beast-mcmc#966]
Hi 
I wonder if there is any BEAUTI distribution that includes the GLM model  (for identifying predictors as described in the tutorial (http://beast.community/workshop_discrete_diffusion#exercise-2-identifying-predictors-for-the-host-switching-process)
I am using currently Beauti 1.8.4 but the option is not available. Is there a new beta version available? Should I move back to a previous version?
thanks,

![screen shot 2017-10-28 at 3 51 22 pm](https://user-images.githubusercontent.com/18502631/32139252-63f8919c-bbf8-11e7-830b-3d7b87353add.png)

**Comment by rambaut** [comment]
This list is for logging bugs and issues with the software so am closing this. However, downloading and compiling the code in this GitHub repository will give you the latest version. We will also be posting a preview version soon.
