### ISSUE TITLE
BEAUti option to 'Reconstruct complete change history on tree' does not work

### ISSUE THREAD

**Issue by plemey** [beast-dev/beast-mcmc#967]
The option in the 'States' panel to 'Reconstruct complete change history on tree' does not seem to work. What is needed to make this work is the following arguments in the markovJumpsTreeLikelihood:
saveCompleteHistory="true" logCompleteHistory="true" useUniformization="true"
And a reference to the markovJumpsTreeLikelihood in the tree log (not embedded in a 'trait' element).

I would like to take the opportunity to also ask for a 'Save complete change history to log' option. This also needs the same arguments in markovJumpsTreeLikelihood and the following additional log:
		<log id="completeJumpHistory" logEvery="1000" fileName="batRABV.history.log">
			<completeHistoryLogger>
				<ancestralTreeLikelihood idref="host.treeLikelihood"/>
			</completeHistoryLogger>
		</log>

**Comment by rambaut** [comment]
Added the logCompleteHistory="true" because that was easy. Need to produce a separate tree log file for each partition for which complete history is on.

**Comment by rambaut** [comment]
Now creates a new tree log for each partition that is logging complete history. Need to test before closing issue.
