### ISSUE TITLE
Microsoft Visual C++ Runtime Library Error when running BEAST 

### ISSUE THREAD

**Issue by MarineRobuchon** [beast-dev/beast-mcmc#968]
Hi,
I get the following error message of the Microsoft Visual C++ Runtime Library when running the last version of BEAST (V1.8.4):

> 
Assertion failed!
Program: mmon
Files\libhmsbeagle\hmsbeagle-cpu-sse32-21.DLL
File: C:\developer\beagle-lib\libhmsbeagl.../BeagleC...mpl.php
Line: 2246

Expression: size > 0

For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts
(Press Retry to debug the application - JIT must be enabled)
> 

I updated the Microsoft Visual C++ Runtime Library, restarted the computer, but it did not change anything. Any idea how to fix it?

Thank you for your help!

Marine

**Comment by MarineRobuchon** [comment]
Hi again, 
I tried to run BEAST without using BEAGLE with the same XML input to try to understand what is wrong. Here is the message printed:

> 

Failed to load native NucleotideLikelihoodCore in : C:\Program Files\BEAST v1.8.4\lib\
Using Java nucleotide likelihood core because java.lang.UnsatisfiedLinkError: C:\Program Files\BEAST v1.8.4\lib\NucleotideLikelihoodCore.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
WARNING: Likelihood component, branchRates, created but not used in the MCMC
Nov 06, 2017 4:22:45 PM dr.app.beast.BeastMain <init>
SEVERE: Error running file: XMLinput_carnivore-tree_Nyakakura2012.xml
Nov 06, 2017 4:22:45 PM dr.app.beast.BeastMain <init>
SEVERE: The initial model is invalid because state has a zero probability.

> 

I did the same with a different XML input (the "Flu" XML file provided in example with BEAST).
Here is the message printed:

> 

Failed to load native NucleotideLikelihoodCore in : C:\Program Files\BEAST v1.8.4\lib\
Using Java nucleotide likelihood core because java.lang.UnsatisfiedLinkError: C:\Program Files\BEAST v1.8.4\lib\NucleotideLikelihoodCore.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
reeLikelihood(treeModel) using Java nucleotide likelihood core
  Ignoring ambiguities in tree likelihood.
  With 148 unique site patterns.
Branch rate model used: strictClockBranchRates
Parameter weights for delta exchange are: 566	566	566	
Likelihood computation is using an auto sizing thread pool.

BEAST has terminated with an error. Please select QUIT from the menu.
dr.xml.XMLParseException: Error parsing '<log>' element with id, 'fileLog':
File 'C:\Program Files\BEAST v1.8.4\examples\VirusPractical\Flu\Flu.log' can not be opened for log element.
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
Nov 06, 2017 4:32:18 PM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, Flu.xml:
Error parsing '<log>' element with id, 'fileLog':
File 'C:\Program Files\BEAST v1.8.4\examples\VirusPractical\Flu\Flu.log' can not be opened for log element.
java.lang.RuntimeException: Terminate
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

> 

So apparently, I have at least one problem with Java (though I installed the latest version and restarted my computer) which prevents me to  load native NucleotideLikelihoodCore.

Any advice would be greatly appreciated!

Cheers,

Marine

**Comment by msuchard** [comment]
This is almost certainly an Oracle/Microsoft turf war issue and not a BEAST or BEAGLE issue.  You need to install a 64-bit version of Java.

**Comment by MarineRobuchon** [comment]
Hi Marc,
Thank for your answer!
I uninstalled the Java version I had on my computer and then re-installed a 64-bit version of Java. I checked via the cmd that it was a 64-bit version of Java (see print_CMD attached) and run again BEAST with the XML file Flu, but I still have the following error messages :

**1) USING BEAGLE**
BEAST has terminated with an error. Please select QUIT from the menu.
Nov 07, 2017 10:36:53 AM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, Flu.xml:
Error parsing '<log>' element with id, 'fileLog':
File 'C:\Program Files\BEAST v1.8.4\examples\VirusPractical\Flu\Flu.log' can not be opened for log element.
java.lang.RuntimeException: Terminate
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

**2) WITHOUT BEAGLE**
Failed to load native NucleotideLikelihoodCore in : C:\Program Files\BEAST v1.8.4\lib\
Using Java nucleotide likelihood core because java.lang.UnsatisfiedLinkError: C:\Program Files\BEAST v1.8.4\lib\NucleotideLikelihoodCore.dll: L’application n’a pas pu démarrer car sa configuration côte-à-côte est incorrecte. Pour plus d’informations, consultez le journal des événements des applications ou utilisez l’outil de ligne de commande sxstrace.exe

BEAST has terminated with an error. Please select QUIT from the menu.
dr.xml.XMLParseException: Error parsing '<log>' element with id, 'fileLog':
File 'C:\Program Files\BEAST v1.8.4\examples\VirusPractical\Flu\Flu.log' can not be opened for log element.
	at dr.xml.AbstractXMLObjectParser.parseXMLObject(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.convert(Unknown Source)
	at dr.xml.XMLParser.parse(Unknown Source)
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)
Nov 07, 2017 10:38:45 AM dr.app.beast.BeastMain <init>
SEVERE: Parsing error - poorly formed BEAST file, Flu.xml:
Error parsing '<log>' element with id, 'fileLog':
File 'C:\Program Files\BEAST v1.8.4\examples\VirusPractical\Flu\Flu.log' can not be opened for log element.
java.lang.RuntimeException: Terminate
	at dr.app.beast.BeastMain.<init>(Unknown Source)
	at dr.app.beast.BeastMain.main(Unknown Source)

Which version of Java are you using? I can try to use the same and see if I still have error messages.

Thank you for your help,

Marine


![print_cmd](https://user-images.githubusercontent.com/15787613/32486848-27716746-c3a8-11e7-8637-7db1da9e1ea6.png)

**Comment by rambaut** [comment]
I am closing this because it is not a BEAST issue - this discussion could continue on the beast-user discussion group. 

However, quickly:
> File 'C:\Program Files\BEAST v1.8.4\examples\VirusPractical\Flu\Flu.log' can not be opened for log element.

This is a separate issue. It is saying it can't create the file possibly because the directory is locked or read-only? Try running it in a different folder.
