### ISSUE TITLE
Wrong deafult setting for microsatellite substitution models

### ISSUE THREAD

**Issue by carlopacioni** [beast-dev/beast-mcmc#973]
When generating an xml file for microsatellite data analysis with EL1, EL2, PC1 or PC2 substitution models in BEAUti 1.8.4, I believe that the argument `estimateSubmodelParameters` of the node `LINEARBIASModel` takes the wrong value. I think it should take the value `false` for EL and `true` for PC substitution models.

Thanks!

**Comment by rambaut** [comment]
Microsatellites are depricated in BEAUti now.
