### ISSUE TITLE
saving xml files

### ISSUE THREAD

**Issue by antoine4ucsd** [beast-dev/beast-mcmc#974]
Hi
I am a long time user of BEAST mostly from a Mac OS. 
I recently noticed that beauti does not save xml file properly: the last windows to direct the new xml file (see attached) only shows up occasionally and I had to restart beauti multiple times.
I am using both Beauti 1.8.4 and the pre-released 2017 version.
Are you aware of this issue? it does not happen on my linux or PC. Is it related to the most recent IOS?

thanks in advance and have a great Holidays season
a

![screen shot 2017-12-25 at 7 52 42 am](https://user-images.githubusercontent.com/18502631/34341261-9c24ada8-e948-11e7-8384-c06e74357564.png)

**Comment by rambaut** [comment]
This is not something I have seen happen - nor has it been reported by others. It is possibly something specific to the particular machine. Closing for now.
