### ISSUE TITLE
Relabel the 'posterior' column in log files?

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#982]
Probably should relabel it to make it clear that it is not the posterior density. What should it be called? 'Bayesian numerator'? 'log(prior . likelihood)'?  'sum(log densities)'?

**Comment by GuyBaele** [comment]
For clarity, I like the log(prior . likelihood) option if it's complemented with separate log(prior) and log(likelihood) entries as well.

**Comment by rambaut** [comment]
Or perhaps just 'joint' as we omit 'density' from 'prior'?

**Comment by rambaut** [comment]
Or change 'prior' to 'prior density' as well.

**Comment by msuchard** [comment]
Am happy with `joint` and `prior`.

**Comment by alexeid** [comment]
isn’t it the unnormalized posterior density?

**Comment by rambaut** [comment]
Changed to 'joint' as the most succinct term that isn't wrong.
