### ISSUE TITLE
question marks and data type in BEAUti

### ISSUE THREAD

**Issue by maxbiostat** [beast-dev/beast-mcmc#986]
If you load an aligment with just `???` as sequence (as a way to sample from the prior, for instance), BEAUti automatically recognises it as aminoacid data, and you can't change it.

**Comment by shimul83** [comment]
Hi maxbiostat, I am trying to do use BEAST but it is really difficult. Can you please give me some suggestions?

**Comment by maxbiostat** [comment]
@shimul83 this thread is not the appropriate venue. If you have a concrete problem using beast, please post it on https://groups.google.com/forum/#!forum/beast-users and we will try and help you. If you think the problem you're facing is a bug, then feel free to open an issue on this repository and we'll take a look.

**Comment by rambaut** [comment]
Probably better to use N for missing nucleotide and X for missing amino acids. Will make ? default to nucleotide.
