### ISSUE TITLE
The -beagle_off command line option should be removed.

### ISSUE THREAD

**Issue by rambaut** [beast-dev/beast-mcmc#995]
BEAST now only uses BEAGLE for its CTMC likelihood calculations so turning off BEAGLE (with the `-beagle_off` command line option) is ignored. The option should be removed or a message printed to say it will be ignored.

**Comment by GuyBaele** [comment]
I think removing the option would be best, which is what I have done. I have adjusted the text in the GUI to indicate that the BEAGLE library is required to run BEAST.
