### ISSUE TITLE
change default prior on yule.birthRate

### ISSUE THREAD

**Issue by GuyBaele** [beast-dev/beast-mcmc#998]
Currently, a Uniform[0, 1E100] is placed on the yule.birthRate parameter by default. This creates problems for generalized stepping-stone sampling as the priors are taken into account when computing the marginal likelihood and this prior is far off what anyone would want given that its expected value is incredibly high. I suggest to change this to one of the lognormal priors, such as for the transition/transversion ratio for example.

**Comment by rambaut** [comment]
Sounds reasonable.
