### ISSUE TITLE
erroneous data specification when format is in yyyy-dd-mm

### ISSUE THREAD

**Issue by bramvrancken** [beast-dev/beast-mcmc#999]
Just tried an example where the date format was is yyyy-dd-mm. This is accepted by BEAUTi when reading the dates as 'parse with variable precision', but the dates are incorrectly converted to decimal format. This can lead to errors when the dates are not carefully checked when the xml is created.
Example:
>KX547173_USA_NewYork_Orleans_2005-31-8
ATGTCTAAGAAACCAGGAGGGCCCGGCAAGAGCCGGGCTG
>KX547347_USA_NewYork_Monroe_2005-25-5
ATGTCTAAGAAACCAGGAGGGCCCGGCAAGAGCCGGGCTG

Perhaps it's worthwhile to include a sanity check for the date format?
B.

**Comment by rambaut** [comment]
yyyy-dd-mm is not a reasonable date format and should never be used. The whole point of yyyy-mm-dd is that it is ISO 8601 and is unambiguous. The 'variable precision' uses the unambiguity of it to specify the uncertainty (i.e., you can drop the day or the day and the month).

**Comment by rambaut** [comment]
How does one even test for this date format?

**Comment by rambaut** [comment]
Collection date in genbank entry for KX547173 is given as:
/collection_date="31-Aug-2005"

Who on earth converted this to a date format that is only used in Kazakhstan and Latvia?

https://en.wikipedia.org/wiki/Date_format_by_country
